// PRACTICE bank for 表現読解 — Part III question type 8 (10 questions on the real exam).
// This section tests INTENDED meaning, not literal meaning. Japanese business speech refuses,
// pressures and warns indirectly, and the exam builds its wrong options out of the literal reading.
// Every item carries a full hiragana reading and English meanings for the review layer.
// Not official BJT material.

export interface ExpressionItem {
  id: string;
  /** Register/function group, used for filtering and for progress reporting. */
  group: "refusal" | "request" | "warning" | "agreement" | "hedging";
  context: string;
  passage: string;
  passageReading: string;
  passageMeaning: string;
  question: string;
  questionReading: string;
  questionMeaning: string;
  options: string[];
  optionMeanings: string[];
  correctIndex: number;
  /** One-line "what it actually means" for the study/flashcard layer. */
  realMeaning: string;
  explanation: string;
}

export const expressionGroupInfo: Record<ExpressionItem["group"], { label: string; note: string }> = {
  refusal: { label: "Indirect refusal", note: "Japanese business rarely says no outright. Learn the shapes a no takes." },
  request: { label: "Softened request", note: "The politer the wrapping, the more binding the request usually is." },
  warning: { label: "Warning / prohibition", note: "Notices forbid things gently. Read them as rules, not suggestions." },
  agreement: { label: "Agreement & commitment", note: "Distinguish a real yes from a placeholder yes." },
  hedging: { label: "Hedging & deferral", note: "Phrases that postpone a decision without refusing it." },
};

export const expressionItems: ExpressionItem[] = [
  {
    id: "ex-1", group: "refusal",
    context: "You have proposed a price to a client. The client replies:",
    passage: "その件につきましては、社内で検討させていただきます。",
    passageReading: "そのけんにつきましては、しゃないでけんとうさせていただきます。",
    passageMeaning: "As for that matter, we will consider it internally.",
    question: "この返事の本当の意味に最も近いのはどれですか。",
    questionReading: "このへんじのほんとうのいみにもっともちかいのはどれですか。",
    questionMeaning: "Which is closest to the true meaning of this reply?",
    options: ["断る可能性が高い", "すぐに契約する", "値段を上げてほしい", "もう決定している"],
    optionMeanings: ["It is likely a refusal", "They will sign immediately", "They want a higher price", "It is already decided"],
    correctIndex: 0,
    realMeaning: "検討します = a polite no, most of the time.",
    explanation: "検討します literally means 'we'll consider it', but in a business reply to a proposal it is the standard soft refusal. If a client genuinely intends to proceed they signal it — 前向きに進めたい, ぜひお願いします. Absent that, treat 検討します as a no and follow up rather than waiting.",
  },
  {
    id: "ex-2", group: "refusal",
    context: "You ask a supplier to bring the delivery date forward. They answer:",
    passage: "納期の前倒しは、ちょっと難しいですね。",
    passageReading: "のうきのまえだおしは、ちょっとむずかしいですね。",
    passageMeaning: "Moving the delivery date up is a little difficult, isn't it.",
    question: "相手は納期を早めますか。",
    questionReading: "あいてはのうきをはやめますか。",
    questionMeaning: "Will the other party bring the delivery date forward?",
    options: ["早める", "早めない", "半分だけ早める", "まだ分からない"],
    optionMeanings: ["Yes", "No", "Only partly", "Undecided"],
    correctIndex: 1,
    realMeaning: "難しい = impossible, not 'challenging but doable'.",
    explanation: "難しいです in business Japanese means no. It is not an invitation to negotiate harder — softening it further with ちょっと makes the refusal more polite, not more open. English speakers routinely misread this as 'difficult but possible'.",
  },
  {
    id: "ex-3", group: "refusal",
    context: "You invite a client to dinner after the meeting. They say:",
    passage: "せっかくのお誘いですが、あいにく先約がございまして。",
    passageReading: "せっかくのおさそいですが、あいにくせんやくがございまして。",
    passageMeaning: "It's a kind invitation, but unfortunately I have a prior engagement.",
    question: "相手は食事に行きますか。",
    questionReading: "あいてはしょくじにいきますか。",
    questionMeaning: "Will they come to dinner?",
    options: ["行く", "行かない", "遅れて行く", "次回は必ず行く"],
    optionMeanings: ["Yes", "No", "Will come late", "Will definitely come next time"],
    correctIndex: 1,
    realMeaning: "せっかくですが + reason = a complete, polite decline.",
    explanation: "The sentence trails off at ございまして without finishing — that unfinished ending IS the refusal, and finishing it would be blunt. せっかくのお誘いですが acknowledges the offer before declining it. Note the answer is not '次回は' — nothing about a future occasion was promised.",
  },
  {
    id: "ex-4", group: "refusal",
    context: "You propose a new supplier at a meeting. Your manager responds:",
    passage: "面白い提案だけど、今回は見送らせていただこうかな。",
    passageReading: "おもしろいていあんだけど、こんかいはみおくらせていただこうかな。",
    passageMeaning: "It's an interesting proposal, but I think we'll pass this time.",
    question: "提案はどうなりましたか。",
    questionReading: "ていあんはどうなりましたか。",
    questionMeaning: "What happened to the proposal?",
    options: ["採用された", "今回は採用されなかった", "修正して再提出することになった", "上司が気に入らなかった"],
    optionMeanings: ["Accepted", "Not adopted this time", "To be revised and resubmitted", "The boss disliked it"],
    correctIndex: 1,
    realMeaning: "見送る = to pass on something, to decline for now.",
    explanation: "見送る literally means 'to see off', but with a proposal it means declining to proceed. 面白い提案だけど is praise used as a cushion — do not read it as approval. 今回は leaves the door open for a future attempt without promising one.",
  },
  {
    id: "ex-5", group: "hedging",
    context: "You ask a client for a decision. They reply:",
    passage: "私の一存では決めかねますので、上の者と相談いたします。",
    passageReading: "わたしのいちぞんではきめかねますので、うえのものとそうだんいたします。",
    passageMeaning: "I cannot decide on my own authority, so I will consult my superiors.",
    question: "この人について正しいものはどれですか。",
    questionReading: "このひとについてただしいものはどれですか。",
    questionMeaning: "Which is true about this person?",
    options: ["決定する権限がない", "提案を断っている", "すでに決定した", "上司に不満がある"],
    optionMeanings: ["Lacks the authority to decide", "Is refusing the proposal", "Has already decided", "Is unhappy with their boss"],
    correctIndex: 0,
    realMeaning: "一存では決めかねます = this is above my authority, not a refusal.",
    explanation: "〜かねます is a formal 'cannot', so 決めかねます = cannot decide. Combined with 一存 (one's own discretion) it states a limit of authority, not an opinion on your proposal. This is genuinely different from 検討します — here a real internal decision follows.",
  },
  {
    id: "ex-6", group: "warning",
    context: "A notice is posted in the office kitchen:",
    passage: "私物の放置はご遠慮ください。",
    passageReading: "しぶつのほうちはごえんりょください。",
    passageMeaning: "Please refrain from leaving personal belongings here.",
    question: "この掲示は何を伝えていますか。",
    questionReading: "このけいじはなにをつたえていますか。",
    questionMeaning: "What does this notice communicate?",
    options: ["私物を置いてはいけない", "私物を置いてもよい", "私物を持ち帰るのは禁止", "遠慮せずに使ってよい"],
    optionMeanings: ["You must not leave belongings", "You may leave belongings", "Taking belongings home is banned", "Feel free to use it"],
    correctIndex: 0,
    realMeaning: "ご遠慮ください = prohibited, phrased politely.",
    explanation: "ご遠慮ください looks like a request for restraint but functions as a ban. The trap option plays on 遠慮 meaning 'reserve/hesitation' — 遠慮なく (without hesitation) means the opposite, so the presence or absence of なく flips the whole meaning.",
  },
  {
    id: "ex-7", group: "warning",
    context: "An email about a schedule ends with:",
    passage: "なお、変更の可能性がある旨、お含みおきください。",
    passageReading: "なお、へんこうのかのうせいがあるむね、おふくみおきください。",
    passageMeaning: "Please also be aware that there is a possibility of changes.",
    question: "受け取った人はどうすべきですか。",
    questionReading: "うけとったひとはどうすべきですか。",
    questionMeaning: "What should the recipient do?",
    options: ["変更があるかもしれないと理解しておく", "すぐに返信する", "予定を変更する", "上司に報告する"],
    optionMeanings: ["Understand that changes may occur", "Reply immediately", "Change their own schedule", "Report to their boss"],
    correctIndex: 0,
    realMeaning: "お含みおきください = please bear this in mind (no action required).",
    explanation: "お含みおきください asks the reader to hold information in mind — it requests understanding, not action. 旨 (むね) means 'to the effect that' and marks the content being conveyed. No reply is expected, which is what separates it from ご確認ください.",
  },
  {
    id: "ex-8", group: "request",
    context: "A colleague writes to you:",
    passage: "お手数をおかけしますが、明日までにご確認いただけますと幸いです。",
    passageReading: "おてすうをおかけしますが、あすまでにごかくにんいただけますとさいわいです。",
    passageMeaning: "Sorry to trouble you, but I would be grateful if you could check by tomorrow.",
    question: "これはどういう依頼ですか。",
    questionReading: "これはどういういらいですか。",
    questionMeaning: "What kind of request is this?",
    options: ["明日までに確認してほしい", "確認は不要である", "明日以降でよい", "自分で確認すると言っている"],
    optionMeanings: ["Please check by tomorrow", "No checking needed", "Any time after tomorrow is fine", "They will check it themselves"],
    correctIndex: 0,
    realMeaning: "〜いただけますと幸いです = a real deadline, softly worded.",
    explanation: "〜と幸いです ('I would be glad if') sounds optional in English but functions as a polite instruction with a firm deadline. Treat 明日までに as binding. The politeness signals respect for the reader's time, not flexibility about the date.",
  },
  {
    id: "ex-9", group: "request",
    context: "A client emails you:",
    passage: "差し支えなければ、見積書を再度お送りいただけますでしょうか。",
    passageReading: "さしつかえなければ、みつもりしょをさいどおおくりいただけますでしょうか。",
    passageMeaning: "If it's not inconvenient, could you send the quotation again?",
    question: "差し支えなければ の意味はどれですか。",
    questionReading: "さしつかえなければのいみはどれですか。",
    questionMeaning: "What does 差し支えなければ mean?",
    options: ["問題がなければ", "急ぎでなければ", "無料であれば", "興味があれば"],
    optionMeanings: ["If there's no problem", "If it's not urgent", "If it's free", "If you're interested"],
    correctIndex: 0,
    realMeaning: "差し支えなければ = if it causes you no problem (a courtesy opener).",
    explanation: "差し支え means a hindrance or problem, so 差し支えなければ = 'if it's no trouble'. It is a courtesy wrapper on a request that the sender fully expects to be granted. Recognising these openers quickly frees up reading time for the real content.",
  },
  {
    id: "ex-10", group: "agreement",
    context: "After you explain a plan, your client says:",
    passage: "おっしゃる通りだと存じます。その方向で進めましょう。",
    passageReading: "おっしゃるとおりだとぞんじます。そのほうこうですすめましょう。",
    passageMeaning: "I believe you are quite right. Let's proceed in that direction.",
    question: "相手の態度はどれですか。",
    questionReading: "あいてのたいどはどれですか。",
    questionMeaning: "What is the other party's attitude?",
    options: ["賛成して前に進める", "やんわり断っている", "判断を保留している", "反対している"],
    optionMeanings: ["Agreeing and moving forward", "Gently refusing", "Reserving judgement", "Opposing"],
    correctIndex: 0,
    realMeaning: "その方向で進めましょう = a genuine yes.",
    explanation: "This is what real agreement looks like: 進めましょう commits to action with a volitional form. Contrast it with 検討します or 考えておきます, which commit to nothing. The presence of a concrete next step is the reliable marker of a true yes.",
  },
  {
    id: "ex-11", group: "hedging",
    context: "You ask your manager about your proposal from last week. They say:",
    passage: "その件は前向きに検討しているところです。",
    passageReading: "そのけんはまえむきにけんとうしているところです。",
    passageMeaning: "We are considering that matter positively at the moment.",
    question: "この返事の解釈として最も適切なものはどれですか。",
    questionReading: "このへんじのかいしゃくとしてもっともてきせつなものはどれですか。",
    questionMeaning: "Which is the most appropriate interpretation?",
    options: ["まだ結論は出ていない", "すでに承認された", "完全に却下された", "今日中に決まる"],
    optionMeanings: ["No conclusion has been reached yet", "Already approved", "Completely rejected", "Will be decided today"],
    correctIndex: 0,
    realMeaning: "前向きに検討中 = still undecided, leaning favourable at best.",
    explanation: "前向きに softens 検討 toward the positive, and 〜ているところです marks an action in progress. Together they describe an open process, not a decision. Choosing 'already approved' over-reads the optimism; choosing 'rejected' ignores 前向きに.",
  },
  {
    id: "ex-12", group: "refusal",
    context: "A junior colleague offers to help you carry documents. You want to decline. Which is correct?",
    passage: "（部下の申し出を断る場面）",
    passageReading: "（ぶかのもうしでをことわるばめん）",
    passageMeaning: "(A situation where you decline a subordinate's offer)",
    question: "最も適切な断り方はどれですか。",
    questionReading: "もっともてきせつなことわりかたはどれですか。",
    questionMeaning: "Which is the most appropriate way to decline?",
    options: ["ありがとう、大丈夫です。", "いりません。", "結構です、いりません。", "遠慮します。"],
    optionMeanings: ["Thanks, I'm fine.", "I don't need it.", "No thanks, I don't need it.", "I'll refrain."],
    correctIndex: 0,
    realMeaning: "Thank first, then decline — bare refusals sound cold.",
    explanation: "Declining an offer in Japanese starts with thanks. いりません alone is blunt to the point of rudeness, and 結構です can land as curt when stacked with いりません. 遠慮します is used for declining invitations you were formally offered, not casual help.",
  },
  {
    id: "ex-13", group: "warning",
    context: "An internal memo states:",
    passage: "本資料の社外への持ち出しは固くお断りいたします。",
    passageReading: "ほんしりょうのしゃがいへのもちだしはかたくおことわりいたします。",
    passageMeaning: "Taking this document outside the company is strictly prohibited.",
    question: "この文の意味として正しいものはどれですか。",
    questionReading: "このぶんのいみとしてただしいものはどれですか。",
    questionMeaning: "Which correctly states the meaning?",
    options: ["社外に持ち出してはいけない", "許可を取れば持ち出せる", "社内でも見てはいけない", "コピーだけ持ち出せる"],
    optionMeanings: ["Must not be taken outside", "May be taken out with permission", "Must not be viewed even internally", "Only copies may be taken out"],
    correctIndex: 0,
    realMeaning: "固くお断りいたします = an absolute prohibition.",
    explanation: "お断りいたします is humble in form but absolute in force, and 固く ('firmly') removes any room for exception. No permission route is mentioned, so the option offering one adds information the text does not contain — a standard 表現読解 distractor.",
  },
  {
    id: "ex-14", group: "hedging",
    context: "You chase an overdue reply. The client writes:",
    passage: "確認の上、追ってご連絡申し上げます。",
    passageReading: "かくにんのうえ、おってごれんらくもうしあげます。",
    passageMeaning: "After checking, we will contact you in due course.",
    question: "いつ連絡が来ますか。",
    questionReading: "いつれんらくがきますか。",
    questionMeaning: "When will they get in touch?",
    options: ["確認が済み次第、時期は未定", "今日中", "一週間後と決まっている", "連絡は来ない"],
    optionMeanings: ["Once checking is done; timing unspecified", "By today", "Exactly one week later", "They won't contact you"],
    correctIndex: 0,
    realMeaning: "追って = later, at an unspecified time.",
    explanation: "追って means 'subsequently' with no date attached, and 〜の上 means 'after doing'. The message commits to contact but not to timing — so if you need a date you must ask for one. Reading 追って as a promise of speed is the mistake this item targets.",
  },
  {
    id: "ex-15", group: "request",
    context: "Your manager says at the end of a meeting:",
    passage: "この件、田中さんにお願いできるかな。",
    passageReading: "このけん、たなかさんにおねがいできるかな。",
    passageMeaning: "This matter — could I ask Tanaka to handle it, I wonder.",
    question: "田中さんはどうすべきですか。",
    questionReading: "たなかさんはどうすべきですか。",
    questionMeaning: "What should Tanaka do?",
    options: ["引き受けて対応する", "断ってもよい質問なので断る", "他の人に回す", "返事をしなくてよい"],
    optionMeanings: ["Accept and handle it", "It's optional, so decline", "Pass it to someone else", "No reply needed"],
    correctIndex: 0,
    realMeaning: "できるかな from a superior is an assignment, not a question.",
    explanation: "〜かな sounds tentative and self-directed, but from a manager to a subordinate it is a softened instruction. The tentativeness is politeness, not genuine optionality. Answering 'no' would be a serious misread of the hierarchy.",
  },
  {
    id: "ex-16", group: "refusal",
    context: "A client responds to your invoice query:",
    passage: "そちらのご事情は承知しておりますが、社内規定上、対応いたしかねます。",
    passageReading: "そちらのごじじょうはしょうちしておりますが、しゃないきていじょう、たいおういたしかねます。",
    passageMeaning: "We understand your circumstances, but under internal regulations we are unable to accommodate this.",
    question: "相手は要望に応じますか。",
    questionReading: "あいてはようぼうにおうじますか。",
    questionMeaning: "Will they accommodate the request?",
    options: ["応じる", "応じない", "条件次第で応じる", "上司なら応じる"],
    optionMeanings: ["Yes", "No", "Depends on conditions", "Their boss would"],
    correctIndex: 1,
    realMeaning: "いたしかねます = we cannot / will not do it.",
    explanation: "〜かねます is a formal negative: 対応いたしかねます = we cannot accommodate. The preceding 承知しております acknowledges your position out of politeness before refusing, so do not read it as partial agreement. 規定上 gives the refusal an impersonal justification.",
  },
  {
    id: "ex-17", group: "agreement",
    context: "You ask a colleague to swap shifts. They reply:",
    passage: "ええ、構いませんよ。",
    passageReading: "ええ、かまいませんよ。",
    passageMeaning: "Sure, I don't mind.",
    question: "相手は交代してくれますか。",
    questionReading: "あいてはこうたいしてくれますか。",
    questionMeaning: "Will they swap?",
    options: ["してくれる", "してくれない", "条件がある", "迷惑がっている"],
    optionMeanings: ["Yes", "No", "There are conditions", "They're annoyed"],
    correctIndex: 0,
    realMeaning: "構いません = I don't mind / that's fine (a yes).",
    explanation: "構いません means 'it doesn't bother me' and is a genuine agreement. It is easy to misread as negative because of the ません ending — but the negative attaches to 'mind', so negating it produces consent. Compare with 結構です, which usually declines.",
  },
  {
    id: "ex-18", group: "warning",
    context: "A note on a shared printer reads:",
    passage: "用紙の補充にご協力をお願いいたします。",
    passageReading: "ようしのほじゅうにごきょうりょくをおねがいいたします。",
    passageMeaning: "We ask for your cooperation in refilling the paper.",
    question: "この掲示は何を求めていますか。",
    questionReading: "このけいじはなにをもとめていますか。",
    questionMeaning: "What is this notice asking for?",
    options: ["使った人が紙を補充すること", "紙を使わないこと", "総務部に連絡すること", "印刷を減らすこと"],
    optionMeanings: ["Users should refill the paper", "Don't use paper", "Contact general affairs", "Print less"],
    correctIndex: 0,
    realMeaning: "ご協力をお願いします = please do this yourself.",
    explanation: "ご協力をお願いいたします is the standard workplace formula for 'everyone is expected to do this'. It reads as a polite appeal but functions as an instruction to the reader. 補充 (replenishment) names the specific action being asked for.",
  },
  {
    id: "ex-19", group: "hedging",
    context: "Asked whether a deadline can be met, a team member says:",
    passage: "できないことはないのですが、品質は保証しかねます。",
    passageReading: "できないことはないのですが、ひんしつはほしょうしかねます。",
    passageMeaning: "It's not that it can't be done, but I can't guarantee the quality.",
    question: "この人の立場に最も近いのはどれですか。",
    questionReading: "このひとのたちばにもっともちかいのはどれですか。",
    questionMeaning: "Which is closest to this person's position?",
    options: ["やればできるが、おすすめしない", "絶対にできない", "問題なくできる", "すでに終わっている"],
    optionMeanings: ["Doable but not advisable", "Absolutely impossible", "Can do it without problems", "Already finished"],
    correctIndex: 0,
    realMeaning: "できないことはない = technically possible, but I'm warning you.",
    explanation: "できないことはない is a double negative meaning 'it's not impossible' — grudging possibility. Pairing it with 保証しかねます turns the sentence into a warning: you can have it on time or good, not both. Reading only the first clause gives the wrong answer.",
  },
  {
    id: "ex-20", group: "refusal",
    context: "A vendor offers a gift at year end. You must decline. The correct phrase is:",
    passage: "（お中元を辞退する場面）",
    passageReading: "（おちゅうげんをじたいするばめん）",
    passageMeaning: "(A situation where you decline a seasonal gift)",
    question: "最も適切な表現はどれですか。",
    questionReading: "もっともてきせつなひょうげんはどれですか。",
    questionMeaning: "Which expression is most appropriate?",
    options: ["お気持ちだけありがたく頂戴いたします。", "そんなものはいりません。", "受け取れません。", "だめです。"],
    optionMeanings: ["I'll gratefully accept the thought alone.", "I don't want such a thing.", "I can't accept it.", "No."],
    correctIndex: 0,
    realMeaning: "お気持ちだけ頂戴します = declining the gift while accepting the gesture.",
    explanation: "お気持ちだけ頂戴いたします declines the object while honouring the intention — the standard way to refuse a gift without causing offence. The other options refuse the gesture itself, which damages the relationship even when the words are grammatically polite.",
  },
  {
    id: "ex-21", group: "request",
    context: "An email opens with:",
    passage: "突然のご連絡失礼いたします。",
    passageReading: "とつぜんのごれんらくしつれいいたします。",
    passageMeaning: "Please excuse this sudden contact.",
    question: "この書き出しから分かることはどれですか。",
    questionReading: "このかきだしからわかることはどれですか。",
    questionMeaning: "What can be inferred from this opening?",
    options: ["初めて連絡する相手である", "長い付き合いの相手である", "苦情のメールである", "社内の同僚宛てである"],
    optionMeanings: ["A first-time contact", "A long-standing relationship", "A complaint email", "Addressed to an in-house colleague"],
    correctIndex: 0,
    realMeaning: "突然のご連絡 = we have not corresponded before.",
    explanation: "突然のご連絡失礼いたします opens a cold approach to someone you have no prior relationship with. An existing contact would get いつもお世話になっております instead — the two openers are mutually exclusive, and the exam uses that contrast to test whether you can identify the relationship from the first line alone.",
  },
  {
    id: "ex-22", group: "agreement",
    context: "You propose a delivery date. The client replies:",
    passage: "そちらで結構でございます。",
    passageReading: "そちらでけっこうでございます。",
    passageMeaning: "That will be fine.",
    question: "この場合の「結構」の意味はどれですか。",
    questionReading: "このばあいの「けっこう」のいみはどれですか。",
    questionMeaning: "What does 結構 mean here?",
    options: ["それでよい（承諾）", "いらない（断り）", "すばらしい（称賛）", "まだ決められない"],
    optionMeanings: ["That's acceptable (agreement)", "No thanks (refusal)", "Splendid (praise)", "Cannot decide yet"],
    correctIndex: 0,
    realMeaning: "結構です can mean yes OR no — the particle decides.",
    explanation: "結構 is genuinely ambiguous and the exam knows it. そちらで結構です ('that will do') accepts a proposal, whereas a bare 結構です in response to an offer declines it. The particle で marks what is being accepted, which is the clue that separates the two readings.",
  },
];

export function expressionItemsByGroup(group: ExpressionItem["group"]) {
  return expressionItems.filter((i) => i.group === group);
}
