import { KanjiItem } from "./types";

// Source: kanji explicitly named in Part 27 (Weeks 1-4 sessions) and Part 9 category tables.
// Readings/meanings/compounds are standard dictionary facts attached to the document's named kanji.
export const kanjiItems: KanjiItem[] = [
  // Numbers/time — W1D1, W1D2
  { id: "k-1", kanji: "一", reading: "いち", meaning: "one", compounds: [{ text: "一つ", reading: "ひとつ" }, { text: "一月", reading: "いちがつ" }], category: "Numbers / Time", week: 1 },
  { id: "k-2", kanji: "二", reading: "に", meaning: "two", compounds: [{ text: "二つ", reading: "ふたつ" }, { text: "二月", reading: "にがつ" }], category: "Numbers / Time", week: 1 },
  { id: "k-3", kanji: "三", reading: "さん", meaning: "three", compounds: [{ text: "三時", reading: "さんじ" }, { text: "三月", reading: "さんがつ" }], category: "Numbers / Time", week: 1 },
  { id: "k-4", kanji: "四", reading: "よん / し", meaning: "four", compounds: [{ text: "四時", reading: "よじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-5", kanji: "五", reading: "ご", meaning: "five", compounds: [{ text: "五時", reading: "ごじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-6", kanji: "六", reading: "ろく", meaning: "six", compounds: [{ text: "六時", reading: "ろくじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-7", kanji: "七", reading: "なな / しち", meaning: "seven", compounds: [{ text: "七時", reading: "しちじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-8", kanji: "八", reading: "はち", meaning: "eight", compounds: [{ text: "八時", reading: "はちじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-9", kanji: "九", reading: "きゅう / く", meaning: "nine", compounds: [{ text: "九時", reading: "くじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-10", kanji: "十", reading: "じゅう", meaning: "ten", compounds: [{ text: "十時", reading: "じゅうじ" }], category: "Numbers / Time", week: 1 },
  { id: "k-hyaku", kanji: "百", reading: "ひゃく", meaning: "hundred", compounds: [{ text: "百円", reading: "ひゃくえん" }], category: "Money", week: 1 },
  { id: "k-sen", kanji: "千", reading: "せん", meaning: "thousand", compounds: [{ text: "千円", reading: "せんえん" }], category: "Money", week: 1 },
  { id: "k-en", kanji: "円", reading: "えん", meaning: "yen / circle", compounds: [{ text: "百円", reading: "ひゃくえん" }, { text: "千円", reading: "せんえん" }], category: "Money", week: 1 },
  { id: "k-nen", kanji: "年", reading: "ねん", meaning: "year", compounds: [{ text: "今年", reading: "ことし" }, { text: "来年", reading: "らいねん" }], category: "Numbers / Time", week: 2 },
  { id: "k-getsu", kanji: "月", reading: "がつ / つき", meaning: "month / moon", compounds: [{ text: "来月", reading: "らいげつ" }, { text: "先月", reading: "せんげつ" }], category: "Numbers / Time", week: 2 },
  { id: "k-nichi", kanji: "日", reading: "にち / ひ", meaning: "day / sun", compounds: [{ text: "今日", reading: "きょう" }, { text: "毎日", reading: "まいにち" }], category: "Numbers / Time", week: 2 },
  { id: "k-ji", kanji: "時", reading: "じ", meaning: "time / hour", compounds: [{ text: "時間", reading: "じかん" }, { text: "三時", reading: "さんじ" }], category: "Numbers / Time", week: 2 },
  { id: "k-fun", kanji: "分", reading: "ふん / ぷん", meaning: "minute", compounds: [{ text: "十分", reading: "じゅっぷん" }, { text: "五分", reading: "ごふん" }], category: "Numbers / Time", week: 2 },
  // Company/meeting — W1D3
  { id: "k-kai", kanji: "会", reading: "かい", meaning: "meet / association", compounds: [{ text: "会社", reading: "かいしゃ" }, { text: "会議", reading: "かいぎ" }], category: "Companies / People", week: 3 },
  { id: "k-sha", kanji: "社", reading: "しゃ", meaning: "company / shrine", compounds: [{ text: "会社", reading: "かいしゃ" }, { text: "社員", reading: "しゃいん" }], category: "Companies / People", week: 3 },
  { id: "k-bu", kanji: "部", reading: "ぶ", meaning: "department / part", compounds: [{ text: "部長", reading: "ぶちょう" }, { text: "部下", reading: "ぶか" }], category: "Companies / People", week: 3 },
  { id: "k-ka", kanji: "課", reading: "か", meaning: "section (org unit)", compounds: [{ text: "課長", reading: "かちょう" }], category: "Companies / People", week: 3 },
  { id: "k-gi", kanji: "議", reading: "ぎ", meaning: "discussion / deliberation", compounds: [{ text: "会議", reading: "かいぎ" }, { text: "議題", reading: "ぎだい" }], category: "Meetings", week: 3 },
  // Documents/report — W2D1
  { id: "k-sho", kanji: "書", reading: "しょ", meaning: "write / document", compounds: [{ text: "書類", reading: "しょるい" }], category: "Documents", week: 5 },
  { id: "k-rui", kanji: "類", reading: "るい", meaning: "kind / category", compounds: [{ text: "書類", reading: "しょるい" }], category: "Documents", week: 5 },
  { id: "k-hou", kanji: "報", reading: "ほう", meaning: "report / news", compounds: [{ text: "報告", reading: "ほうこく" }], category: "Documents", week: 5 },
  { id: "k-koku", kanji: "告", reading: "こく", meaning: "tell / announce", compounds: [{ text: "報告", reading: "ほうこく" }], category: "Documents", week: 5 },
  // Schedule — W2D2
  { id: "k-yo", kanji: "予", reading: "よ", meaning: "beforehand", compounds: [{ text: "予定", reading: "よてい" }, { text: "予約", reading: "よやく" }], category: "Schedules", week: 6 },
  { id: "k-tei", kanji: "定", reading: "てい", meaning: "fix / decide", compounds: [{ text: "予定", reading: "よてい" }, { text: "決定", reading: "けってい" }], category: "Schedules", week: 6 },
  { id: "k-shime", kanji: "締", reading: "しめ", meaning: "tighten / close", compounds: [{ text: "締め切り", reading: "しめきり" }], category: "Schedules", week: 6 },
  { id: "k-setsu", kanji: "切", reading: "せつ / きり", meaning: "cut / limit", compounds: [{ text: "締切", reading: "しめきり" }, { text: "大切", reading: "たいせつ" }], category: "Schedules", week: 6 },
  // Confirm/request — W2D3
  { id: "k-kaku", kanji: "確", reading: "かく", meaning: "confirm / certain", compounds: [{ text: "確認", reading: "かくにん" }], category: "Documents", week: 6 },
  { id: "k-nin", kanji: "認", reading: "にん", meaning: "acknowledge / recognize", compounds: [{ text: "確認", reading: "かくにん" }], category: "Documents", week: 6 },
  { id: "k-i", kanji: "依", reading: "い", meaning: "depend / request", compounds: [{ text: "依頼", reading: "いらい" }], category: "Instructions", week: 6 },
  { id: "k-rai", kanji: "頼", reading: "らい", meaning: "rely / ask", compounds: [{ text: "依頼", reading: "いらい" }], category: "Instructions", week: 6 },
  // Phone — W3D1
  { id: "k-den", kanji: "電", reading: "でん", meaning: "electricity", compounds: [{ text: "電話", reading: "でんわ" }, { text: "電車", reading: "でんしゃ" }], category: "Transport", week: 9 },
  { id: "k-wa", kanji: "話", reading: "わ", meaning: "talk / speech", compounds: [{ text: "電話", reading: "でんわ" }], category: "Companies / People", week: 9 },
  { id: "k-ban", kanji: "番", reading: "ばん", meaning: "number / order", compounds: [{ text: "番号", reading: "ばんごう" }], category: "Companies / People", week: 9 },
  { id: "k-gou", kanji: "号", reading: "ごう", meaning: "number / issue", compounds: [{ text: "番号", reading: "ばんごう" }], category: "Companies / People", week: 9 },
  // Customer — W3D2
  { id: "k-kyaku", kanji: "客", reading: "きゃく", meaning: "guest / customer", compounds: [{ text: "お客様", reading: "おきゃくさま" }, { text: "接客", reading: "せっきゃく" }], category: "Companies / People", week: 10 },
  { id: "k-tai", kanji: "対", reading: "たい", meaning: "face / against", compounds: [{ text: "対応", reading: "たいおう" }, { text: "対策", reading: "たいさく" }], category: "Problems", week: 10 },
  { id: "k-ou", kanji: "応", reading: "おう", meaning: "respond", compounds: [{ text: "対応", reading: "たいおう" }], category: "Problems", week: 10 },
  // Problem/cause — W3D3
  { id: "k-mon", kanji: "問", reading: "もん", meaning: "question / problem; ask / visit", compounds: [{ text: "問題", reading: "もんだい" }, { text: "訪問", reading: "ほうもん" }, { text: "質問", reading: "しつもん" }], category: "Problems", week: 11 },
  { id: "k-dai", kanji: "題", reading: "だい", meaning: "topic / subject", compounds: [{ text: "問題", reading: "もんだい" }, { text: "議題", reading: "ぎだい" }], category: "Problems", week: 11 },
  { id: "k-gen", kanji: "原", reading: "げん", meaning: "origin / field", compounds: [{ text: "原因", reading: "げんいん" }], category: "Problems", week: 11 },
  { id: "k-in", kanji: "因", reading: "いん", meaning: "cause", compounds: [{ text: "原因", reading: "げんいん" }], category: "Problems", week: 11 },
  // Appointments — W4D1
  { id: "k-yaku", kanji: "約", reading: "やく", meaning: "promise / approx. / contract", compounds: [{ text: "予約", reading: "よやく" }, { text: "約束", reading: "やくそく" }, { text: "契約", reading: "けいやく" }], category: "Schedules", week: 13 },
  { id: "k-men", kanji: "面", reading: "めん", meaning: "face / surface", compounds: [{ text: "面会", reading: "めんかい" }], category: "Companies / People", week: 13 },
  { id: "k-hou2", kanji: "訪", reading: "ほう", meaning: "visit", compounds: [{ text: "訪問", reading: "ほうもん" }], category: "Schedules", week: 13 },
  // Decision/opinion — W4D2
  { id: "k-ketsu", kanji: "決", reading: "けつ", meaning: "decide", compounds: [{ text: "決定", reading: "けってい" }], category: "Meetings", week: 14 },
  { id: "k-i2", kanji: "意", reading: "い", meaning: "mind / meaning", compounds: [{ text: "意見", reading: "いけん" }], category: "Meetings", week: 14 },
  { id: "k-ken", kanji: "見", reading: "けん", meaning: "see / opinion", compounds: [{ text: "意見", reading: "いけん" }, { text: "見積", reading: "みつもり" }], category: "Meetings", week: 14 },
  // Quantities — W4D3
  { id: "k-zou", kanji: "増", reading: "ぞう", meaning: "increase", compounds: [{ text: "増加", reading: "ぞうか" }], category: "Quantities", week: 15 },
  { id: "k-gen2", kanji: "減", reading: "げん", meaning: "decrease", compounds: [{ text: "減少", reading: "げんしょう" }], category: "Quantities", week: 15 },
  { id: "k-wari", kanji: "割", reading: "わり", meaning: "ratio / divide", compounds: [{ text: "割合", reading: "わりあい" }], category: "Quantities", week: 15 },
  { id: "k-gou2", kanji: "合", reading: "ごう", meaning: "fit / combine", compounds: [{ text: "割合", reading: "わりあい" }, { text: "合計", reading: "ごうけい" }], category: "Quantities", week: 15 },
  // Additional Part 9 category kanji not yet listed
  { id: "k-youbi", kanji: "曜", reading: "よう", meaning: "day of week", compounds: [{ text: "曜日", reading: "ようび" }], category: "Numbers / Time", week: 2 },
  { id: "k-kin", kanji: "金", reading: "きん", meaning: "money / gold", compounds: [{ text: "料金", reading: "りょうきん" }, { text: "現金", reading: "げんきん" }], category: "Money", week: 2 },
  { id: "k-ryou", kanji: "料", reading: "りょう", meaning: "fee / material", compounds: [{ text: "料金", reading: "りょうきん" }, { text: "資料", reading: "しりょう" }], category: "Money", week: 2 },
  { id: "k-hi", kanji: "費", reading: "ひ", meaning: "expense / cost", compounds: [{ text: "経費", reading: "けいひ" }, { text: "費用", reading: "ひよう" }], category: "Money", week: 17 },
  { id: "k-ka2", kanji: "価", reading: "か", meaning: "price / value", compounds: [{ text: "価格", reading: "かかく" }], category: "Money", week: 17 },
  { id: "k-sei", kanji: "請", reading: "せい", meaning: "request / bill", compounds: [{ text: "請求", reading: "せいきゅう" }], category: "Money", week: 12 },
  { id: "k-shi", kanji: "支", reading: "し", meaning: "branch / pay", compounds: [{ text: "支払", reading: "しはらい" }], category: "Money", week: 12 },
  { id: "k-in2", kanji: "員", reading: "いん", meaning: "member / staff", compounds: [{ text: "社員", reading: "しゃいん" }, { text: "会員", reading: "かいいん" }], category: "Companies / People", week: 5 },
  { id: "k-tan", kanji: "担", reading: "たん", meaning: "bear / undertake", compounds: [{ text: "担当", reading: "たんとう" }], category: "Companies / People", week: 5 },
  { id: "k-touchaku", kanji: "着", reading: "ちゃく", meaning: "arrive / wear", compounds: [{ text: "到着", reading: "とうちゃく" }], category: "Transport", week: 21 },
  { id: "k-shutsu", kanji: "出", reading: "しゅつ / で", meaning: "exit / leave", compounds: [{ text: "出発", reading: "しゅっぱつ" }, { text: "提出", reading: "ていしゅつ" }], category: "Transport", week: 21 },
  { id: "k-hatsu", kanji: "発", reading: "はつ", meaning: "departure / emit", compounds: [{ text: "出発", reading: "しゅっぱつ" }, { text: "発注", reading: "はっちゅう" }], category: "Transport", week: 21 },
  { id: "k-chi", kanji: "遅", reading: "ち", meaning: "late / slow", compounds: [{ text: "遅延", reading: "ちえん" }, { text: "遅刻", reading: "ちこく" }], category: "Transport", week: 21 },
  { id: "k-en2", kanji: "延", reading: "えん", meaning: "extend / postpone", compounds: [{ text: "延期", reading: "えんき" }, { text: "遅延", reading: "ちえん" }], category: "Schedules", week: 21 },
  { id: "k-keiyaku", kanji: "契", reading: "けい", meaning: "contract (part)", compounds: [{ text: "契約", reading: "けいやく" }], category: "Documents", week: 17 },
  { id: "k-shiji", kanji: "指", reading: "し", meaning: "finger / point out", compounds: [{ text: "指示", reading: "しじ" }], category: "Instructions", week: 6 },
  { id: "k-kyoka", kanji: "許", reading: "きょ", meaning: "permit", compounds: [{ text: "許可", reading: "きょか" }], category: "Instructions", week: 7 },
  { id: "k-ka3", kanji: "可", reading: "か", meaning: "possible / permit", compounds: [{ text: "許可", reading: "きょか" }], category: "Instructions", week: 7 },
  { id: "k-chuui", kanji: "注", reading: "ちゅう", meaning: "pour / attention", compounds: [{ text: "注意", reading: "ちゅうい" }, { text: "注文", reading: "ちゅうもん" }], category: "Instructions", week: 9 },
  { id: "k-kin2", kanji: "禁", reading: "きん", meaning: "prohibit", compounds: [{ text: "禁止", reading: "きんし" }], category: "Instructions", week: 9 },
  { id: "k-koshou", kanji: "故", reading: "こ", meaning: "reason / breakdown", compounds: [{ text: "故障", reading: "こしょう" }], category: "Problems", week: 11 },
  { id: "k-shou", kanji: "障", reading: "しょう", meaning: "obstacle", compounds: [{ text: "故障", reading: "こしょう" }], category: "Problems", week: 11 },
  { id: "k-suu", kanji: "数", reading: "すう", meaning: "number / count", compounds: [{ text: "数量", reading: "すうりょう" }], category: "Quantities", week: 15 },
  { id: "k-ryou2", kanji: "量", reading: "りょう", meaning: "amount / quantity", compounds: [{ text: "数量", reading: "すうりょう" }, { text: "分量", reading: "ぶんりょう" }], category: "Quantities", week: 15 },
  // ── Extended business kanji ──
  { id: "k-shu", kanji: "取", reading: "しゅ", meaning: "take / obtain", compounds: [{ text: "取引", reading: "とりひき" }, { text: "取得", reading: "しゅとく" }], category: "Companies / People", week: 7 },
  { id: "k-in3", kanji: "引", reading: "いん", meaning: "pull / withdraw", compounds: [{ text: "取引", reading: "とりひき" }, { text: "割引", reading: "わりびき" }], category: "Companies / People", week: 7 },
  { id: "k-sama", kanji: "様", reading: "さま", meaning: "honorific suffix / manner", compounds: [{ text: "お客様", reading: "おきゃくさま" }, { text: "様子", reading: "ようす" }], category: "Companies / People", week: 7 },
  { id: "k-chou", kanji: "長", reading: "ちょう", meaning: "long / chief", compounds: [{ text: "部長", reading: "ぶちょう" }, { text: "社長", reading: "しゃちょう" }], category: "Companies / People", week: 3 },
  { id: "k-ka4", kanji: "下", reading: "か", meaning: "below / subordinate", compounds: [{ text: "部下", reading: "ぶか" }, { text: "以下", reading: "いか" }], category: "Companies / People", week: 3 },
  { id: "k-jou", kanji: "上", reading: "じょう", meaning: "above / superior", compounds: [{ text: "上司", reading: "じょうし" }, { text: "以上", reading: "いじょう" }], category: "Companies / People", week: 3 },
  { id: "k-shi2", kanji: "司", reading: "し", meaning: "administer", compounds: [{ text: "上司", reading: "じょうし" }], category: "Companies / People", week: 3 },
  { id: "k-sen2", kanji: "先", reading: "せん", meaning: "ahead / previous", compounds: [{ text: "先方", reading: "せんぽう" }, { text: "先週", reading: "せんしゅう" }], category: "Companies / People", week: 7 },
  { id: "k-hou3", kanji: "方", reading: "ほう", meaning: "direction / person", compounds: [{ text: "先方", reading: "せんぽう" }, { text: "方針", reading: "ほうしん" }], category: "Companies / People", week: 7 },
  { id: "k-shi3", kanji: "資", reading: "し", meaning: "resources / capital", compounds: [{ text: "資料", reading: "しりょう" }, { text: "資金", reading: "しきん" }], category: "Documents", week: 5 },
  { id: "k-kaku2", kanji: "格", reading: "かく", meaning: "status / standard", compounds: [{ text: "価格", reading: "かかく" }, { text: "資格", reading: "しかく" }], category: "Money", week: 17 },
  { id: "k-hin", kanji: "品", reading: "ひん", meaning: "goods / quality", compounds: [{ text: "商品", reading: "しょうひん" }, { text: "品質", reading: "ひんしつ" }], category: "Sales", week: 12 },
  { id: "k-shou2", kanji: "商", reading: "しょう", meaning: "commerce", compounds: [{ text: "商品", reading: "しょうひん" }, { text: "商談", reading: "しょうだん" }], category: "Sales", week: 12 },
  { id: "k-zai", kanji: "在", reading: "ざい", meaning: "exist / stock", compounds: [{ text: "在庫", reading: "ざいこ" }, { text: "不在", reading: "ふざい" }], category: "Sales", week: 12 },
  { id: "k-ko", kanji: "庫", reading: "こ", meaning: "warehouse", compounds: [{ text: "在庫", reading: "ざいこ" }, { text: "倉庫", reading: "そうこ" }], category: "Sales", week: 12 },
  { id: "k-nou", kanji: "納", reading: "のう", meaning: "deliver / pay in", compounds: [{ text: "納品", reading: "のうひん" }, { text: "納期", reading: "のうき" }], category: "Delivery", week: 12 },
  { id: "k-ki", kanji: "期", reading: "き", meaning: "period / term", compounds: [{ text: "期限", reading: "きげん" }, { text: "納期", reading: "のうき" }], category: "Schedules", week: 6 },
  { id: "k-gen3", kanji: "限", reading: "げん", meaning: "limit", compounds: [{ text: "期限", reading: "きげん" }, { text: "制限", reading: "せいげん" }], category: "Schedules", week: 6 },
  { id: "k-hen", kanji: "変", reading: "へん", meaning: "change / strange", compounds: [{ text: "変更", reading: "へんこう" }, { text: "大変", reading: "たいへん" }], category: "Schedules", week: 6 },
  { id: "k-kou2", kanji: "更", reading: "こう", meaning: "renew / further", compounds: [{ text: "変更", reading: "へんこう" }, { text: "更新", reading: "こうしん" }], category: "Schedules", week: 6 },
  { id: "k-san", kanji: "参", reading: "さん", meaning: "participate / humble go", compounds: [{ text: "参加", reading: "さんか" }, { text: "参考", reading: "さんこう" }], category: "Meetings", week: 4 },
  { id: "k-ka5", kanji: "加", reading: "か", meaning: "add", compounds: [{ text: "参加", reading: "さんか" }, { text: "追加", reading: "ついか" }], category: "Meetings", week: 4 },
  { id: "k-seki", kanji: "席", reading: "せき", meaning: "seat", compounds: [{ text: "出席", reading: "しゅっせき" }, { text: "座席", reading: "ざせき" }], category: "Meetings", week: 4 },
  { id: "k-ketsu2", kanji: "欠", reading: "けつ", meaning: "lack / absent", compounds: [{ text: "欠席", reading: "けっせき" }, { text: "欠品", reading: "けっぴん" }], category: "Meetings", week: 4 },
  { id: "k-kai2", kanji: "開", reading: "かい", meaning: "open / start", compounds: [{ text: "開始", reading: "かいし" }, { text: "開催", reading: "かいさい" }], category: "Schedules", week: 6 },
  { id: "k-shi4", kanji: "始", reading: "し", meaning: "begin", compounds: [{ text: "開始", reading: "かいし" }], category: "Schedules", week: 6 },
  { id: "k-shuu2", kanji: "終", reading: "しゅう", meaning: "end", compounds: [{ text: "終了", reading: "しゅうりょう" }, { text: "最終", reading: "さいしゅう" }], category: "Schedules", week: 6 },
  { id: "k-ryou3", kanji: "了", reading: "りょう", meaning: "finish / understand", compounds: [{ text: "終了", reading: "しゅうりょう" }, { text: "完了", reading: "かんりょう" }], category: "Schedules", week: 6 },
  { id: "k-jou2", kanji: "場", reading: "じょう", meaning: "place / venue", compounds: [{ text: "会場", reading: "かいじょう" }, { text: "工場", reading: "こうじょう" }], category: "Schedules", week: 6 },
  { id: "k-sho2", kanji: "所", reading: "しょ", meaning: "place", compounds: [{ text: "場所", reading: "ばしょ" }, { text: "事務所", reading: "じむしょ" }], category: "Schedules", week: 6 },
  { id: "k-ren", kanji: "連", reading: "れん", meaning: "connect", compounds: [{ text: "連絡", reading: "れんらく" }, { text: "関連", reading: "かんれん" }], category: "Instructions", week: 6 },
  { id: "k-raku", kanji: "絡", reading: "らく", meaning: "entwine / contact", compounds: [{ text: "連絡", reading: "れんらく" }], category: "Instructions", week: 6 },
  { id: "k-sou", kanji: "相", reading: "そう", meaning: "mutual / consult", compounds: [{ text: "相談", reading: "そうだん" }, { text: "相手", reading: "あいて" }], category: "Instructions", week: 8 },
  { id: "k-dan", kanji: "談", reading: "だん", meaning: "talk / discuss", compounds: [{ text: "相談", reading: "そうだん" }, { text: "商談", reading: "しょうだん" }], category: "Instructions", week: 8 },
  { id: "k-shou3", kanji: "承", reading: "しょう", meaning: "consent / receive", compounds: [{ text: "承認", reading: "しょうにん" }, { text: "承知", reading: "しょうち" }], category: "Instructions", week: 8 },
  { id: "k-bun", kanji: "文", reading: "ぶん", meaning: "sentence / writing", compounds: [{ text: "注文", reading: "ちゅうもん" }, { text: "文書", reading: "ぶんしょ" }], category: "Documents", week: 9 },
  { id: "k-tei2", kanji: "提", reading: "てい", meaning: "present / propose", compounds: [{ text: "提出", reading: "ていしゅつ" }, { text: "提案", reading: "ていあん" }], category: "Documents", week: 5 },
  { id: "k-an", kanji: "案", reading: "あん", meaning: "plan / proposal", compounds: [{ text: "提案", reading: "ていあん" }, { text: "案内", reading: "あんない" }], category: "Meetings", week: 14 },
  { id: "k-ken2", kanji: "検", reading: "けん", meaning: "examine", compounds: [{ text: "検討", reading: "けんとう" }, { text: "検品", reading: "けんぴん" }], category: "Meetings", week: 14 },
  { id: "k-tou", kanji: "討", reading: "とう", meaning: "discuss / examine", compounds: [{ text: "検討", reading: "けんとう" }], category: "Meetings", week: 14 },
  { id: "k-jitsu", kanji: "実", reading: "じつ", meaning: "truth / actual", compounds: [{ text: "実施", reading: "じっし" }, { text: "実績", reading: "じっせき" }], category: "Instructions", week: 16 },
  { id: "k-shi5", kanji: "施", reading: "し", meaning: "carry out", compounds: [{ text: "実施", reading: "じっし" }, { text: "施設", reading: "しせつ" }], category: "Instructions", week: 16 },
  { id: "k-ei", kanji: "営", reading: "えい", meaning: "manage / operate", compounds: [{ text: "営業", reading: "えいぎょう" }, { text: "経営", reading: "けいえい" }], category: "Sales", week: 12 },
  { id: "k-gyou", kanji: "業", reading: "ぎょう", meaning: "business / work", compounds: [{ text: "営業", reading: "えいぎょう" }, { text: "業務", reading: "ぎょうむ" }], category: "Sales", week: 12 },
  { id: "k-bai", kanji: "売", reading: "ばい", meaning: "sell", compounds: [{ text: "売上", reading: "うりあげ" }, { text: "販売", reading: "はんばい" }], category: "Sales", week: 12 },
  { id: "k-you", kanji: "用", reading: "よう", meaning: "use / business", compounds: [{ text: "使用", reading: "しよう" }, { text: "用件", reading: "ようけん" }], category: "Instructions", week: 9 },
];

export const kanjiTotalTarget = 1000; // Source: Part 9 — 700-1,000 recognised in business compounds
export const kanjiWeeklyTarget = { min: 12, max: 16 }; // Source: Part 9

export function kanjiCategories() {
  return Array.from(new Set(kanjiItems.map((k) => k.category))).sort();
}
