import { VocabItem } from "./types";

// Source: Part 27 word sets (all 12 named 10-word sets from Weeks 1-4) + Part 8 cluster examples.
// These are every concrete vocabulary item the source document names by kanji.
// Weekly targets beyond these (e.g. "Reports/orders 50") are tracked as category volume goals — see vocabCategoryTargets below —
// since the source gives cluster names + counts for weeks 5-24 rather than an exhaustive word list.
export const vocabulary: VocabItem[] = [
  // Week 1 D1 — Office basics
  { id: "v-kaisha", japanese: "会社", reading: "かいしゃ", meaning: "company", category: "Office & People", month: 1, example: "私の会社は大分県にあります。", exampleMeaning: "My company is in Oita Prefecture." },
  { id: "v-shigoto", japanese: "仕事", reading: "しごと", meaning: "work / job", category: "Office & People", month: 1, example: "今日は仕事が忙しいです。", exampleMeaning: "Work is busy today." },
  { id: "v-kaigi", japanese: "会議", reading: "かいぎ", meaning: "meeting", category: "Meetings", month: 1, example: "会議は3時です。", exampleMeaning: "The meeting is at 3 o'clock." },
  { id: "v-shiryou", japanese: "資料", reading: "しりょう", meaning: "materials / documents", category: "Documents", month: 1, example: "資料を送っていただけますか。", exampleMeaning: "Could you send me the documents?" },
  { id: "v-denwa", japanese: "電話", reading: "でんわ", meaning: "telephone / phone call", category: "Telephone", month: 1, example: "電話がかかってきました。", exampleMeaning: "A phone call came in." },
  { id: "v-buchou", japanese: "部長", reading: "ぶちょう", meaning: "department manager", category: "Office & People", month: 1, example: "部長は今、会議中です。", exampleMeaning: "The department manager is in a meeting right now." },
  { id: "v-kachou", japanese: "課長", reading: "かちょう", meaning: "section chief", category: "Office & People", month: 1, example: "課長に相談してから決めます。", exampleMeaning: "I'll decide after consulting the section chief." },
  { id: "v-douryou", japanese: "同僚", reading: "どうりょう", meaning: "colleague", category: "Office & People", month: 1, example: "同僚と一緒にプロジェクトを進めています。", exampleMeaning: "I'm working on the project together with a colleague." },
  { id: "v-namae", japanese: "名前", reading: "なまえ", meaning: "name", category: "Office & People", month: 1, example: "こちらにお名前をご記入ください。", exampleMeaning: "Please write your name here." },
  { id: "v-kyou", japanese: "今日", reading: "きょう", meaning: "today", category: "Numbers & Time", month: 1, example: "今日中にお返事いたします。", exampleMeaning: "I will reply by the end of today." },
  // Week 1 D2 — schedule/time
  { id: "v-jikan", japanese: "時間", reading: "じかん", meaning: "time", category: "Numbers & Time", month: 1, example: "お時間はございますか。", exampleMeaning: "Do you have time (a moment)?" },
  { id: "v-yotei", japanese: "予定", reading: "よてい", meaning: "plan / schedule", category: "Scheduling", month: 1, example: "来週の予定を確認します。", exampleMeaning: "I'll check next week's schedule." },
  { id: "v-ashita", japanese: "明日", reading: "あした", meaning: "tomorrow", category: "Numbers & Time", month: 1, example: "明日までにご返信いただけますか。", exampleMeaning: "Could you reply by tomorrow?" },
  { id: "v-kinou", japanese: "昨日", reading: "きのう", meaning: "yesterday", category: "Numbers & Time", month: 1, example: "昨日の会議の議事録を送ります。", exampleMeaning: "I'll send the minutes from yesterday's meeting." },
  { id: "v-gozen", japanese: "午前", reading: "ごぜん", meaning: "a.m. / morning", category: "Numbers & Time", month: 1, example: "午前中にお電話いたします。", exampleMeaning: "I will call you in the morning." },
  { id: "v-gogo", japanese: "午後", reading: "ごご", meaning: "p.m. / afternoon", category: "Numbers & Time", month: 1, example: "打ち合わせは午後2時からです。", exampleMeaning: "The meeting starts at 2 p.m." },
  { id: "v-shuu", japanese: "週", reading: "しゅう", meaning: "week", category: "Numbers & Time", month: 1, example: "来週もう一度ご連絡します。", exampleMeaning: "I'll contact you again next week." },
  { id: "v-tsuki", japanese: "月", reading: "つき", meaning: "month", category: "Numbers & Time", month: 1, example: "来月、新しい支店がオープンします。", exampleMeaning: "A new branch will open next month." },
  { id: "v-youbi", japanese: "曜日", reading: "ようび", meaning: "day of the week", category: "Numbers & Time", month: 1, example: "ご都合のよい曜日を教えてください。", exampleMeaning: "Please tell me which day of the week is convenient for you." },
  { id: "v-yasumi", japanese: "休み", reading: "やすみ", meaning: "day off / break", category: "Numbers & Time", month: 1, example: "来週、休みをいただく予定です。", exampleMeaning: "I plan to take a day off next week." },
  // Week 1 D3 — scheduling
  { id: "v-shimekiri", japanese: "締め切り", reading: "しめきり", meaning: "deadline", category: "Scheduling", month: 1, example: "締め切りは金曜日です。", exampleMeaning: "The deadline is Friday." },
  { id: "v-kigen", japanese: "期限", reading: "きげん", meaning: "deadline / time limit", category: "Scheduling", month: 1, example: "提出期限を過ぎてしまいました。", exampleMeaning: "I missed the submission deadline." },
  { id: "v-henkou", japanese: "変更", reading: "へんこう", meaning: "change", category: "Scheduling", month: 1, example: "会議の時間を変更してもよろしいですか。", exampleMeaning: "Would it be all right to change the meeting time?" },
  { id: "v-sanka", japanese: "参加", reading: "さんか", meaning: "participation", category: "Meetings", month: 1, example: "研修に参加する予定です。", exampleMeaning: "I plan to participate in the training." },
  { id: "v-shusseki", japanese: "出席", reading: "しゅっせき", meaning: "attendance", category: "Meetings", month: 1, example: "会議に出席できません。", exampleMeaning: "I cannot attend the meeting." },
  { id: "v-kesseki", japanese: "欠席", reading: "けっせき", meaning: "absence", category: "Meetings", month: 1, example: "本日の会議は欠席させていただきます。", exampleMeaning: "I will be absent from today's meeting." },
  { id: "v-kaishi", japanese: "開始", reading: "かいし", meaning: "start / commencement", category: "Scheduling", month: 1, example: "研修は9時に開始します。", exampleMeaning: "The training starts at 9 o'clock." },
  { id: "v-shuuryou", japanese: "終了", reading: "しゅうりょう", meaning: "end / completion", category: "Scheduling", month: 1, example: "会議は5時に終了しました。", exampleMeaning: "The meeting ended at 5 o'clock." },
  { id: "v-basho", japanese: "場所", reading: "ばしょ", meaning: "place / location", category: "Scheduling", month: 1, example: "会議の場所が変更になりました。", exampleMeaning: "The meeting location has been changed." },
  { id: "v-renraku", japanese: "連絡", reading: "れんらく", meaning: "contact / communication", category: "Reports & Orders", month: 1, example: "後ほどご連絡いたします。", exampleMeaning: "I will contact you again later." },
  // Week 2 D1 — people/roles
  { id: "v-shain", japanese: "社員", reading: "しゃいん", meaning: "employee", category: "Office & People", month: 1, example: "新入社員が10名入社しました。", exampleMeaning: "Ten new employees joined the company." },
  { id: "v-joushi", japanese: "上司", reading: "じょうし", meaning: "superior / boss", category: "Office & People", month: 1, example: "上司に確認してからご連絡します。", exampleMeaning: "I'll contact you after checking with my boss." },
  { id: "v-buka", japanese: "部下", reading: "ぶか", meaning: "subordinate", category: "Office & People", month: 1, example: "部下に資料の作成を頼みました。", exampleMeaning: "I asked my subordinate to prepare the materials." },
  { id: "v-tantou", japanese: "担当", reading: "たんとう", meaning: "being in charge / assigned duty", category: "Office & People", month: 1, example: "この案件は私が担当しております。", exampleMeaning: "I am in charge of this matter." },
  { id: "v-okyakusama", japanese: "お客様", reading: "おきゃくさま", meaning: "customer (polite)", category: "Customer Service", month: 2, example: "お客様をお待たせしてしまいました。", exampleMeaning: "I kept the customer waiting." },
  { id: "v-torihikisaki", japanese: "取引先", reading: "とりひきさき", meaning: "business partner / client company", category: "Office & People", month: 2, example: "取引先との打ち合わせがあります。", exampleMeaning: "I have a meeting with a business partner." },
  { id: "v-shachou", japanese: "社長", reading: "しゃちょう", meaning: "company president", category: "Office & People", month: 1, example: "社長がご挨拶に伺います。", exampleMeaning: "The president will come to greet you." },
  { id: "v-uketsuke", japanese: "受付", reading: "うけつけ", meaning: "reception", category: "Office & People", month: 1, example: "1階の受付でお待ちください。", exampleMeaning: "Please wait at the first-floor reception." },
  { id: "v-jimu", japanese: "事務", reading: "じむ", meaning: "office work / clerical", category: "Office & People", month: 1, example: "事務の仕事を担当しています。", exampleMeaning: "I'm in charge of clerical work." },
  { id: "v-eigyou", japanese: "営業", reading: "えいぎょう", meaning: "sales (dept./activity)", category: "Sales", month: 4, example: "営業部で3年間働いています。", exampleMeaning: "I've been working in the sales department for three years." },
  // Week 2 D2 — scheduling 2
  { id: "v-yoyaku", japanese: "予約", reading: "よやく", meaning: "reservation / booking", category: "Scheduling", month: 2, example: "会議室のご予約はお済みですか。", exampleMeaning: "Have you already booked the meeting room?" },
  { id: "v-uchiawase", japanese: "打ち合わせ", reading: "うちあわせ", meaning: "meeting / arrangement", category: "Meetings", month: 2, example: "明日の打ち合わせは何時からですか。", exampleMeaning: "What time does tomorrow's meeting start?" },
  { id: "v-kaijou", japanese: "会場", reading: "かいじょう", meaning: "venue", category: "Meetings", month: 2, example: "会場までの地図をお送りします。", exampleMeaning: "I'll send you a map to the venue." },
  { id: "v-shiryousakusei", japanese: "資料作成", reading: "しりょうさくせい", meaning: "document preparation", category: "Documents", month: 2, example: "資料作成に時間がかかりました。", exampleMeaning: "Preparing the documents took a lot of time." },
  { id: "v-teishutsu", japanese: "提出", reading: "ていしゅつ", meaning: "submission", category: "Documents", month: 2, example: "レポートは金曜日までに提出してください。", exampleMeaning: "Please submit the report by Friday." },
  { id: "v-junbi", japanese: "準備", reading: "じゅんび", meaning: "preparation", category: "Scheduling", month: 2, example: "会議の準備はできています。", exampleMeaning: "The preparation for the meeting is done." },
  { id: "v-chikoku", japanese: "遅刻", reading: "ちこく", meaning: "lateness / being late", category: "Scheduling", month: 2, example: "電車が遅れて、遅刻してしまいました。", exampleMeaning: "The train was delayed, so I ended up being late." },
  { id: "v-soutai", japanese: "早退", reading: "そうたい", meaning: "leaving early", category: "Scheduling", month: 2, example: "体調が悪いので早退させていただきます。", exampleMeaning: "I'll leave early since I'm not feeling well." },
  { id: "v-zangyou", japanese: "残業", reading: "ざんぎょう", meaning: "overtime", category: "Scheduling", month: 2, example: "今日は残業しなければなりません。", exampleMeaning: "I have to work overtime today." },
  { id: "v-shucchou", japanese: "出張", reading: "しゅっちょう", meaning: "business trip", category: "Scheduling", month: 2, example: "来週、大阪へ出張します。", exampleMeaning: "I'll go on a business trip to Osaka next week." },
  // Week 2 D3 — reports/orders
  { id: "v-houkoku", japanese: "報告", reading: "ほうこく", meaning: "report", category: "Reports & Orders", month: 2, example: "進捗を上司に報告しました。", exampleMeaning: "I reported the progress to my boss." },
  { id: "v-soudan", japanese: "相談", reading: "そうだん", meaning: "consultation", category: "Reports & Orders", month: 2, example: "少しご相談したいことがあります。", exampleMeaning: "There's something I'd like to consult you about." },
  { id: "v-chuumon", japanese: "注文", reading: "ちゅうもん", meaning: "order", category: "Reports & Orders", month: 2, example: "追加で注文をお願いします。", exampleMeaning: "I'd like to place an additional order, please." },
  { id: "v-irai", japanese: "依頼", reading: "いらい", meaning: "request", category: "Reports & Orders", month: 2, example: "翻訳の依頼を受けました。", exampleMeaning: "I received a request for translation." },
  { id: "v-kakunin", japanese: "確認", reading: "かくにん", meaning: "confirmation", category: "Reports & Orders", month: 2, example: "確認いたします。", exampleMeaning: "I will check on it (humble)." },
  { id: "v-shounin", japanese: "承認", reading: "しょうにん", meaning: "approval", category: "Reports & Orders", month: 2, example: "部長の承認をいただきました。", exampleMeaning: "I received the department manager's approval." },
  { id: "v-mitsumori", japanese: "見積", reading: "みつもり", meaning: "estimate / quotation", category: "Accounting", month: 4, example: "お見積書をお送りいたします。", exampleMeaning: "I will send you the quotation." },
  { id: "v-seikyuu", japanese: "請求", reading: "せいきゅう", meaning: "invoice / billing", category: "Accounting", month: 4, example: "請求書は月末に発行されます。", exampleMeaning: "The invoice is issued at the end of the month." },
  { id: "v-shiharai", japanese: "支払", reading: "しはらい", meaning: "payment", category: "Accounting", month: 4, example: "お支払いは今月末までにお願いします。", exampleMeaning: "Please make the payment by the end of this month." },
  // Week 3 D1 — telephone
  { id: "v-naisen", japanese: "内線", reading: "ないせん", meaning: "extension (phone)", category: "Telephone", month: 3, example: "内線204におつなぎします。", exampleMeaning: "I'll connect you to extension 204." },
  { id: "v-orikaeshi", japanese: "折り返し", reading: "おりかえし", meaning: "call back", category: "Telephone", month: 3, example: "戻りましたら折り返しお電話いたします。", exampleMeaning: "I will call you back once he/she returns." },
  { id: "v-dengon", japanese: "伝言", reading: "でんごん", meaning: "message", category: "Telephone", month: 3, example: "伝言をお願いできますか。", exampleMeaning: "Could I leave a message?" },
  { id: "v-bangou", japanese: "番号", reading: "ばんごう", meaning: "number", category: "Telephone", month: 3, example: "念のため電話番号を教えてください。", exampleMeaning: "Just in case, please tell me your phone number." },
  { id: "v-yobidashi", japanese: "呼び出し", reading: "よびだし", meaning: "calling / paging", category: "Telephone", month: 3, example: "担当者を呼び出しますので、少々お待ちください。", exampleMeaning: "I'll page the person in charge, so please wait a moment." },
  { id: "v-tsuuwa", japanese: "通話", reading: "つうわ", meaning: "phone call (in progress)", category: "Telephone", month: 3, example: "ただいま他の通話に出ております。", exampleMeaning: "He/she is currently on another call." },
  { id: "v-rusu", japanese: "留守", reading: "るす", meaning: "absence (from home/desk)", category: "Telephone", month: 3, example: "申し訳ございませんが、ただいま留守にしております。", exampleMeaning: "I'm sorry, but he/she is away from the desk right now." },
  { id: "v-fuzai", japanese: "不在", reading: "ふざい", meaning: "not present / away", category: "Telephone", month: 3, example: "田中はただいま不在にしております。", exampleMeaning: "Tanaka is not present right now." },
  { id: "v-tantousha", japanese: "担当者", reading: "たんとうしゃ", meaning: "the person in charge / representative", category: "Telephone", month: 3, example: "担当者に代わりますので、少々お待ちください。", exampleMeaning: "I'll transfer you to the person in charge; please hold." },
  // Week 3 D2 — customer service
  { id: "v-taiou", japanese: "対応", reading: "たいおう", meaning: "response / handling", category: "Customer Service", month: 3, example: "迅速な対応、ありがとうございました。", exampleMeaning: "Thank you for your prompt response." },
  { id: "v-kujou", japanese: "苦情", reading: "くじょう", meaning: "complaint", category: "Customer Service", month: 3, example: "お客様から苦情のお電話がありました。", exampleMeaning: "There was a complaint call from a customer." },
  { id: "v-shazai", japanese: "謝罪", reading: "しゃざい", meaning: "apology", category: "Customer Service", month: 3, example: "改めて謝罪させていただきます。", exampleMeaning: "Allow me to offer my apology once again." },
  { id: "v-koukan", japanese: "交換", reading: "こうかん", meaning: "exchange", category: "Customer Service", month: 3, example: "不良品を新しい商品と交換いたします。", exampleMeaning: "We will exchange the defective item for a new one." },
  { id: "v-henpin", japanese: "返品", reading: "へんぴん", meaning: "returned goods", category: "Customer Service", month: 3, example: "こちらの商品を返品したいのですが。", exampleMeaning: "I'd like to return this item." },
  { id: "v-zaiko", japanese: "在庫", reading: "ざいこ", meaning: "stock / inventory", category: "Sales", month: 4, example: "在庫を確認いたします。", exampleMeaning: "I'll check the stock." },
  { id: "v-shouhin", japanese: "商品", reading: "しょうひん", meaning: "product / merchandise", category: "Customer Service", month: 3, example: "こちらの商品は現在在庫切れです。", exampleMeaning: "This product is currently out of stock." },
  { id: "v-annai", japanese: "案内", reading: "あんない", meaning: "guidance / information", category: "Customer Service", month: 3, example: "会議室までご案内いたします。", exampleMeaning: "I'll guide you to the meeting room." },
  { id: "v-machijikan", japanese: "待ち時間", reading: "まちじかん", meaning: "waiting time", category: "Customer Service", month: 3, example: "現在、お待ち時間は約10分です。", exampleMeaning: "The current waiting time is about ten minutes." },
  // Week 3 D3 — problems/apology
  { id: "v-mondai", japanese: "問題", reading: "もんだい", meaning: "problem", category: "Problems & Solutions", month: 5, example: "システムに問題が発生しました。", exampleMeaning: "A problem occurred with the system." },
  { id: "v-genin", japanese: "原因", reading: "げんいん", meaning: "cause", category: "Problems & Solutions", month: 5, example: "遅延の原因を調査しています。", exampleMeaning: "We are investigating the cause of the delay." },
  { id: "v-taisaku", japanese: "対策", reading: "たいさく", meaning: "countermeasure", category: "Problems & Solutions", month: 5, example: "再発防止の対策を検討します。", exampleMeaning: "We will consider countermeasures to prevent recurrence." },
  { id: "v-kaiketsu", japanese: "解決", reading: "かいけつ", meaning: "solution / resolution", category: "Problems & Solutions", month: 5, example: "問題は無事に解決いたしました。", exampleMeaning: "The problem has been successfully resolved." },
  { id: "v-meiwaku", japanese: "迷惑", reading: "めいわく", meaning: "trouble / inconvenience", category: "Customer Service", month: 3, example: "ご迷惑をおかけして申し訳ございません。", exampleMeaning: "I apologize for the inconvenience caused." },
  { id: "v-teisei", japanese: "訂正", reading: "ていせい", meaning: "correction", category: "Customer Service", month: 3, example: "資料の一部を訂正いたします。", exampleMeaning: "I will correct part of the document." },
  { id: "v-taiouchuu", japanese: "対応中", reading: "たいおうちゅう", meaning: "currently handling", category: "Customer Service", month: 3, example: "現在、担当者が対応中でございます。", exampleMeaning: "The person in charge is currently handling it." },
  { id: "v-shikyuu", japanese: "至急", reading: "しきゅう", meaning: "urgent", category: "Customer Service", month: 3, example: "至急ご確認をお願いいたします。", exampleMeaning: "Please check this urgently." },
  { id: "v-kyoushuku", japanese: "恐縮", reading: "きょうしゅく", meaning: "much obliged / sorry to trouble you", category: "Set Phrases", month: 6, example: "お忙しいところ恐縮ですが、よろしくお願いいたします。", exampleMeaning: "I'm sorry to trouble you when you're busy, but thank you in advance." },
  { id: "v-moushiwake", japanese: "申し訳", reading: "もうしわけ", meaning: "apology (root of 申し訳ございません)", category: "Set Phrases", month: 3, example: "申し訳ございませんが、少々お待ちください。", exampleMeaning: "I'm terribly sorry, but please wait a moment." },
  // Week 4 D1 — appointments
  { id: "v-yakusoku", japanese: "約束", reading: "やくそく", meaning: "promise / appointment", category: "Appointments", month: 2, example: "3時に部長とお約束しております。", exampleMeaning: "I have an appointment with the manager at 3 o'clock." },
  { id: "v-menkai", japanese: "面会", reading: "めんかい", meaning: "meeting / interview (with someone)", category: "Appointments", month: 2, example: "社長との面会を希望しております。", exampleMeaning: "I would like to request a meeting with the president." },
  { id: "v-houmon", japanese: "訪問", reading: "ほうもん", meaning: "visit", category: "Appointments", month: 2, example: "来週、御社を訪問させていただきます。", exampleMeaning: "I will visit your company next week." },
  { id: "v-tsugou", japanese: "都合", reading: "つごう", meaning: "convenience / circumstances", category: "Appointments", month: 2, example: "ご都合のよろしい日をお知らせください。", exampleMeaning: "Please let me know a day that is convenient for you." },
  { id: "v-nittei", japanese: "日程", reading: "にってい", meaning: "schedule / itinerary", category: "Appointments", month: 2, example: "出張の日程を調整しています。", exampleMeaning: "I'm adjusting the itinerary for the business trip." },
  { id: "v-kakutei", japanese: "確定", reading: "かくてい", meaning: "confirmed / finalized", category: "Appointments", month: 2, example: "日程はまだ確定しておりません。", exampleMeaning: "The schedule has not been finalized yet." },
  { id: "v-cancel", japanese: "キャンセル", reading: "キャンセル", meaning: "cancellation", category: "Appointments", month: 2, example: "予約をキャンセルしたいのですが。", exampleMeaning: "I would like to cancel my reservation." },
  { id: "v-aki", japanese: "空き", reading: "あき", meaning: "vacancy / opening", category: "Appointments", month: 2, example: "来週、空きの時間はございますか。", exampleMeaning: "Do you have any openings next week?" },
  { id: "v-chousei", japanese: "調整", reading: "ちょうせい", meaning: "adjustment / coordination", category: "Appointments", month: 2, example: "スケジュールを調整いたします。", exampleMeaning: "I will adjust the schedule." },
  // Week 4 D2 — meetings
  { id: "v-gidai", japanese: "議題", reading: "ぎだい", meaning: "agenda item", category: "Meetings", month: 4, example: "次の議題に移りましょう。", exampleMeaning: "Let's move on to the next agenda item." },
  { id: "v-kettei", japanese: "決定", reading: "けってい", meaning: "decision", category: "Meetings", month: 4, example: "来月から新しい方針が決定しました。", exampleMeaning: "A new policy was decided starting next month." },
  { id: "v-iken", japanese: "意見", reading: "いけん", meaning: "opinion", category: "Meetings", month: 4, example: "ご意見がございましたらお聞かせください。", exampleMeaning: "Please let us know if you have any opinions." },
  { id: "v-sansei", japanese: "賛成", reading: "さんせい", meaning: "agreement / in favor", category: "Meetings", month: 4, example: "その提案に賛成です。", exampleMeaning: "I am in favor of that proposal." },
  { id: "v-hantai", japanese: "反対", reading: "はんたい", meaning: "opposition / against", category: "Meetings", month: 4, example: "一部の社員が反対しています。", exampleMeaning: "Some employees are opposed." },
  { id: "v-teian", japanese: "提案", reading: "ていあん", meaning: "proposal", category: "Meetings", month: 4, example: "新しい提案をさせていただきます。", exampleMeaning: "Allow me to make a new proposal." },
  { id: "v-gijiroku", japanese: "議事録", reading: "ぎじろく", meaning: "meeting minutes", category: "Meetings", month: 4, example: "議事録を作成してメールで送ります。", exampleMeaning: "I'll prepare the minutes and send them by email." },
  { id: "v-shussekisha", japanese: "出席者", reading: "しゅっせきしゃ", meaning: "attendee", category: "Meetings", month: 4, example: "出席者は全部で12名です。", exampleMeaning: "There are twelve attendees in total." },
  { id: "v-shikai", japanese: "司会", reading: "しかい", meaning: "moderator / chair", category: "Meetings", month: 4, example: "本日の司会を務めさせていただきます。", exampleMeaning: "I will be serving as today's moderator." },
  // Week 4 D3 — data/charts
  { id: "v-wariai", japanese: "割合", reading: "わりあい", meaning: "proportion / ratio", category: "Charts & Data", month: 4, example: "海外売上の割合が増えています。", exampleMeaning: "The proportion of overseas sales is increasing." },
  { id: "v-zouka", japanese: "増加", reading: "ぞうか", meaning: "increase", category: "Charts & Data", month: 4, example: "今月の売上は前月より増加しました。", exampleMeaning: "This month's sales increased compared to last month." },
  { id: "v-genshou", japanese: "減少", reading: "げんしょう", meaning: "decrease", category: "Charts & Data", month: 4, example: "来店客数が減少しています。", exampleMeaning: "The number of visiting customers is decreasing." },
  { id: "v-ijou", japanese: "以上", reading: "いじょう", meaning: "and above / or more", category: "Charts & Data", month: 4, example: "参加者は50名以上の見込みです。", exampleMeaning: "We expect 50 or more participants." },
  { id: "v-ika", japanese: "以下", reading: "いか", meaning: "and below / or less", category: "Charts & Data", month: 4, example: "予算は10万円以下に抑えてください。", exampleMeaning: "Please keep the budget to 100,000 yen or less." },
  { id: "v-goukei", japanese: "合計", reading: "ごうけい", meaning: "total", category: "Charts & Data", month: 4, example: "合計金額をご確認ください。", exampleMeaning: "Please check the total amount." },
  { id: "v-heikin", japanese: "平均", reading: "へいきん", meaning: "average", category: "Charts & Data", month: 4, example: "平均で1日20件の問い合わせがあります。", exampleMeaning: "There are an average of 20 inquiries per day." },
  { id: "v-graph", japanese: "グラフ", reading: "グラフ", meaning: "graph", category: "Charts & Data", month: 4, example: "このグラフをご覧ください。", exampleMeaning: "Please take a look at this graph." },
  { id: "v-hyou", japanese: "表", reading: "ひょう", meaning: "table / chart", category: "Charts & Data", month: 4, example: "詳細は下の表にまとめました。", exampleMeaning: "I've summarized the details in the table below." },
  { id: "v-percent", japanese: "パーセント", reading: "パーセント", meaning: "percent", category: "Charts & Data", month: 4, example: "売上は前年比で20パーセント増えました。", exampleMeaning: "Sales increased by 20 percent compared to last year." },
  // Part 8 extra cluster examples not already covered
  { id: "v-kaigishitsu", japanese: "会議室", reading: "かいぎしつ", meaning: "meeting room", category: "Office & People", month: 1, example: "会議室は3階にございます。", exampleMeaning: "The meeting room is on the third floor." },
  { id: "v-uriage", japanese: "売上", reading: "うりあげ", meaning: "sales revenue", category: "Sales", month: 4, example: "今期の売上は目標を上回りました。", exampleMeaning: "This term's sales revenue exceeded the target." },
  { id: "v-nouhin", japanese: "納品", reading: "のうひん", meaning: "delivery of goods", category: "Delivery", month: 4, example: "商品の納品は来週の予定です。", exampleMeaning: "Delivery of the goods is scheduled for next week." },
  { id: "v-hacchuu", japanese: "発注", reading: "はっちゅう", meaning: "placing an order", category: "Sales", month: 4, example: "部品を追加で発注しました。", exampleMeaning: "I placed an additional order for the parts." },
  { id: "v-haisou", japanese: "配送", reading: "はいそう", meaning: "delivery / shipping", category: "Delivery", month: 5, example: "配送状況を確認させていただきます。", exampleMeaning: "Let me check the delivery status." },
  { id: "v-chien", japanese: "遅延", reading: "ちえん", meaning: "delay", category: "Delivery", month: 5, example: "台風の影響で配送に遅延が出ています。", exampleMeaning: "Delivery is delayed due to the typhoon." },
  { id: "v-touchaku", japanese: "到着", reading: "とうちゃく", meaning: "arrival", category: "Delivery", month: 5, example: "荷物は明日の午前中に到着予定です。", exampleMeaning: "The package is expected to arrive tomorrow morning." },
  { id: "v-kisoku", japanese: "規則", reading: "きそく", meaning: "rule / regulation", category: "Workplace Rules", month: 1, example: "会社の規則を確認してください。", exampleMeaning: "Please check the company's rules." },
  { id: "v-kyoka", japanese: "許可", reading: "きょか", meaning: "permission", category: "Workplace Rules", month: 1, example: "上司の許可をいただいてから提出します。", exampleMeaning: "I'll submit it after receiving my boss's permission." },
  { id: "v-shinsei", japanese: "申請", reading: "しんせい", meaning: "application / request (formal)", category: "Workplace Rules", month: 1, example: "有給休暇を申請しました。", exampleMeaning: "I applied for paid leave." },
  { id: "v-shouchi", japanese: "承知", reading: "しょうち", meaning: "understanding / consent (root of 承知しました)", category: "Confirmation & Response", month: 1, example: "承知いたしました。すぐに対応します。", exampleMeaning: "Understood. I will handle it right away." },
  { id: "v-ryoukai", japanese: "了解", reading: "りょうかい", meaning: "understood / roger", category: "Confirmation & Response", month: 1, example: "了解しました。明日までに準備します。", exampleMeaning: "Got it. I'll get it ready by tomorrow." },
];

export const vocabCategoryTargets: { category: string; month: number; target: number }[] = [
  { category: "Office & People", month: 1, target: 200 },
  { category: "Scheduling & Deadlines", month: 2, target: 250 },
  { category: "Telephone", month: 3, target: 60 },
  { category: "Customer Service & Complaints", month: 3, target: 240 },
  { category: "Meetings", month: 4, target: 60 },
  { category: "Sales & Delivery", month: 4, target: 300 },
  { category: "Accounting", month: 4, target: 60 },
  { category: "Problems & Solutions", month: 5, target: 250 },
  { category: "Transport & Logistics", month: 5, target: 60 },
  { category: "Set Phrases (review)", month: 6, target: 250 },
];

export const vocabTotalTarget = 1800; // Source: Part 8 — total after 6 months
export const vocabWeeklyTarget = { min: 60, max: 80 }; // Source: Part 8
export const vocabDailyTarget = { min: 15, max: 20 }; // Source: Part 8

export function vocabCategories() {
  return Array.from(new Set(vocabulary.map((v) => v.category))).sort();
}
