import { VocabItem } from "./types";

// Source: Part 27 word sets (all 12 named 10-word sets from Weeks 1-4) + Part 8 cluster examples.
// These are every concrete vocabulary item the source document names by kanji.
// Weekly targets beyond these (e.g. "Reports/orders 50") are tracked as category volume goals — see vocabCategoryTargets below —
// since the source gives cluster names + counts for weeks 5-24 rather than an exhaustive word list.
export const vocabulary: VocabItem[] = [
  // Week 1 D1 — Office basics
  { id: "v-kaisha", japanese: "会社", reading: "かいしゃ", meaning: "company", category: "Office & People", month: 1, example: "私の会社は大分県にあります。" },
  { id: "v-shigoto", japanese: "仕事", reading: "しごと", meaning: "work / job", category: "Office & People", month: 1, example: "今日は仕事が忙しいです。" },
  { id: "v-kaigi", japanese: "会議", reading: "かいぎ", meaning: "meeting", category: "Meetings", month: 1, example: "会議は3時です。" },
  { id: "v-shiryou", japanese: "資料", reading: "しりょう", meaning: "materials / documents", category: "Documents", month: 1, example: "資料を送っていただけますか。" },
  { id: "v-denwa", japanese: "電話", reading: "でんわ", meaning: "telephone / phone call", category: "Telephone", month: 1, example: "電話がかかってきました。" },
  { id: "v-buchou", japanese: "部長", reading: "ぶちょう", meaning: "department manager", category: "Office & People", month: 1 },
  { id: "v-kachou", japanese: "課長", reading: "かちょう", meaning: "section chief", category: "Office & People", month: 1 },
  { id: "v-douryou", japanese: "同僚", reading: "どうりょう", meaning: "colleague", category: "Office & People", month: 1 },
  { id: "v-namae", japanese: "名前", reading: "なまえ", meaning: "name", category: "Office & People", month: 1 },
  { id: "v-kyou", japanese: "今日", reading: "きょう", meaning: "today", category: "Numbers & Time", month: 1 },
  // Week 1 D2 — schedule/time
  { id: "v-jikan", japanese: "時間", reading: "じかん", meaning: "time", category: "Numbers & Time", month: 1 },
  { id: "v-yotei", japanese: "予定", reading: "よてい", meaning: "plan / schedule", category: "Scheduling", month: 1, example: "来週の予定を確認します。" },
  { id: "v-ashita", japanese: "明日", reading: "あした", meaning: "tomorrow", category: "Numbers & Time", month: 1 },
  { id: "v-kinou", japanese: "昨日", reading: "きのう", meaning: "yesterday", category: "Numbers & Time", month: 1 },
  { id: "v-gozen", japanese: "午前", reading: "ごぜん", meaning: "a.m. / morning", category: "Numbers & Time", month: 1 },
  { id: "v-gogo", japanese: "午後", reading: "ごご", meaning: "p.m. / afternoon", category: "Numbers & Time", month: 1 },
  { id: "v-shuu", japanese: "週", reading: "しゅう", meaning: "week", category: "Numbers & Time", month: 1 },
  { id: "v-tsuki", japanese: "月", reading: "つき", meaning: "month", category: "Numbers & Time", month: 1 },
  { id: "v-youbi", japanese: "曜日", reading: "ようび", meaning: "day of the week", category: "Numbers & Time", month: 1 },
  { id: "v-yasumi", japanese: "休み", reading: "やすみ", meaning: "day off / break", category: "Numbers & Time", month: 1 },
  // Week 1 D3 — scheduling
  { id: "v-shimekiri", japanese: "締め切り", reading: "しめきり", meaning: "deadline", category: "Scheduling", month: 1, example: "締め切りは金曜日です。" },
  { id: "v-kigen", japanese: "期限", reading: "きげん", meaning: "deadline / time limit", category: "Scheduling", month: 1 },
  { id: "v-henkou", japanese: "変更", reading: "へんこう", meaning: "change", category: "Scheduling", month: 1 },
  { id: "v-sanka", japanese: "参加", reading: "さんか", meaning: "participation", category: "Meetings", month: 1 },
  { id: "v-shusseki", japanese: "出席", reading: "しゅっせき", meaning: "attendance", category: "Meetings", month: 1 },
  { id: "v-kesseki", japanese: "欠席", reading: "けっせき", meaning: "absence", category: "Meetings", month: 1 },
  { id: "v-kaishi", japanese: "開始", reading: "かいし", meaning: "start / commencement", category: "Scheduling", month: 1 },
  { id: "v-shuuryou", japanese: "終了", reading: "しゅうりょう", meaning: "end / completion", category: "Scheduling", month: 1 },
  { id: "v-basho", japanese: "場所", reading: "ばしょ", meaning: "place / location", category: "Scheduling", month: 1 },
  { id: "v-renraku", japanese: "連絡", reading: "れんらく", meaning: "contact / communication", category: "Reports & Orders", month: 1 },
  // Week 2 D1 — people/roles
  { id: "v-shain", japanese: "社員", reading: "しゃいん", meaning: "employee", category: "Office & People", month: 1 },
  { id: "v-joushi", japanese: "上司", reading: "じょうし", meaning: "superior / boss", category: "Office & People", month: 1 },
  { id: "v-buka", japanese: "部下", reading: "ぶか", meaning: "subordinate", category: "Office & People", month: 1 },
  { id: "v-tantou", japanese: "担当", reading: "たんとう", meaning: "person in charge", category: "Office & People", month: 1 },
  { id: "v-okyakusama", japanese: "お客様", reading: "おきゃくさま", meaning: "customer (polite)", category: "Customer Service", month: 2 },
  { id: "v-torihikisaki", japanese: "取引先", reading: "とりひきさき", meaning: "business partner / client company", category: "Office & People", month: 2 },
  { id: "v-shachou", japanese: "社長", reading: "しゃちょう", meaning: "company president", category: "Office & People", month: 1 },
  { id: "v-uketsuke", japanese: "受付", reading: "うけつけ", meaning: "reception", category: "Office & People", month: 1 },
  { id: "v-jimu", japanese: "事務", reading: "じむ", meaning: "office work / clerical", category: "Office & People", month: 1 },
  { id: "v-eigyou", japanese: "営業", reading: "えいぎょう", meaning: "sales (dept./activity)", category: "Sales", month: 4 },
  // Week 2 D2 — scheduling 2
  { id: "v-yoyaku", japanese: "予約", reading: "よやく", meaning: "reservation / booking", category: "Scheduling", month: 2 },
  { id: "v-uchiawase", japanese: "打ち合わせ", reading: "うちあわせ", meaning: "meeting / arrangement", category: "Meetings", month: 2 },
  { id: "v-kaijou", japanese: "会場", reading: "かいじょう", meaning: "venue", category: "Meetings", month: 2 },
  { id: "v-shiryousakusei", japanese: "資料作成", reading: "しりょうさくせい", meaning: "document preparation", category: "Documents", month: 2 },
  { id: "v-teishutsu", japanese: "提出", reading: "ていしゅつ", meaning: "submission", category: "Documents", month: 2 },
  { id: "v-junbi", japanese: "準備", reading: "じゅんび", meaning: "preparation", category: "Scheduling", month: 2 },
  { id: "v-chikoku", japanese: "遅刻", reading: "ちこく", meaning: "lateness / being late", category: "Scheduling", month: 2 },
  { id: "v-soutai", japanese: "早退", reading: "そうたい", meaning: "leaving early", category: "Scheduling", month: 2 },
  { id: "v-zangyou", japanese: "残業", reading: "ざんぎょう", meaning: "overtime", category: "Scheduling", month: 2 },
  { id: "v-shucchou", japanese: "出張", reading: "しゅっちょう", meaning: "business trip", category: "Scheduling", month: 2 },
  // Week 2 D3 — reports/orders
  { id: "v-houkoku", japanese: "報告", reading: "ほうこく", meaning: "report", category: "Reports & Orders", month: 2 },
  { id: "v-soudan", japanese: "相談", reading: "そうだん", meaning: "consultation", category: "Reports & Orders", month: 2 },
  { id: "v-chuumon", japanese: "注文", reading: "ちゅうもん", meaning: "order", category: "Reports & Orders", month: 2 },
  { id: "v-irai", japanese: "依頼", reading: "いらい", meaning: "request", category: "Reports & Orders", month: 2 },
  { id: "v-kakunin", japanese: "確認", reading: "かくにん", meaning: "confirmation", category: "Reports & Orders", month: 2, example: "確認いたします。" },
  { id: "v-shounin", japanese: "承認", reading: "しょうにん", meaning: "approval", category: "Reports & Orders", month: 2 },
  { id: "v-mitsumori", japanese: "見積", reading: "みつもり", meaning: "estimate / quotation", category: "Accounting", month: 4 },
  { id: "v-seikyuu", japanese: "請求", reading: "せいきゅう", meaning: "invoice / billing", category: "Accounting", month: 4 },
  { id: "v-shiharai", japanese: "支払", reading: "しはらい", meaning: "payment", category: "Accounting", month: 4 },
  // Week 3 D1 — telephone
  { id: "v-naisen", japanese: "内線", reading: "ないせん", meaning: "extension (phone)", category: "Telephone", month: 3 },
  { id: "v-orikaeshi", japanese: "折り返し", reading: "おりかえし", meaning: "call back", category: "Telephone", month: 3 },
  { id: "v-dengon", japanese: "伝言", reading: "でんごん", meaning: "message", category: "Telephone", month: 3 },
  { id: "v-bangou", japanese: "番号", reading: "ばんごう", meaning: "number", category: "Telephone", month: 3 },
  { id: "v-yobidashi", japanese: "呼び出し", reading: "よびだし", meaning: "calling / paging", category: "Telephone", month: 3 },
  { id: "v-tsuuwa", japanese: "通話", reading: "つうわ", meaning: "phone call (in progress)", category: "Telephone", month: 3 },
  { id: "v-rusu", japanese: "留守", reading: "るす", meaning: "absence (from home/desk)", category: "Telephone", month: 3 },
  { id: "v-fuzai", japanese: "不在", reading: "ふざい", meaning: "not present / away", category: "Telephone", month: 3 },
  { id: "v-tantousha", japanese: "担当者", reading: "たんとうしゃ", meaning: "person in charge", category: "Telephone", month: 3 },
  // Week 3 D2 — customer service
  { id: "v-taiou", japanese: "対応", reading: "たいおう", meaning: "response / handling", category: "Customer Service", month: 3 },
  { id: "v-kujou", japanese: "苦情", reading: "くじょう", meaning: "complaint", category: "Customer Service", month: 3 },
  { id: "v-shazai", japanese: "謝罪", reading: "しゃざい", meaning: "apology", category: "Customer Service", month: 3 },
  { id: "v-koukan", japanese: "交換", reading: "こうかん", meaning: "exchange", category: "Customer Service", month: 3 },
  { id: "v-henpin", japanese: "返品", reading: "へんぴん", meaning: "returned goods", category: "Customer Service", month: 3 },
  { id: "v-zaiko", japanese: "在庫", reading: "ざいこ", meaning: "stock / inventory", category: "Sales", month: 4 },
  { id: "v-shouhin", japanese: "商品", reading: "しょうひん", meaning: "product / merchandise", category: "Customer Service", month: 3 },
  { id: "v-annai", japanese: "案内", reading: "あんない", meaning: "guidance / information", category: "Customer Service", month: 3 },
  { id: "v-machijikan", japanese: "待ち時間", reading: "まちじかん", meaning: "waiting time", category: "Customer Service", month: 3 },
  // Week 3 D3 — problems/apology
  { id: "v-mondai", japanese: "問題", reading: "もんだい", meaning: "problem", category: "Problems & Solutions", month: 5 },
  { id: "v-genin", japanese: "原因", reading: "げんいん", meaning: "cause", category: "Problems & Solutions", month: 5 },
  { id: "v-taisaku", japanese: "対策", reading: "たいさく", meaning: "countermeasure", category: "Problems & Solutions", month: 5 },
  { id: "v-kaiketsu", japanese: "解決", reading: "かいけつ", meaning: "solution / resolution", category: "Problems & Solutions", month: 5 },
  { id: "v-meiwaku", japanese: "迷惑", reading: "めいわく", meaning: "trouble / inconvenience", category: "Customer Service", month: 3 },
  { id: "v-teisei", japanese: "訂正", reading: "ていせい", meaning: "correction", category: "Customer Service", month: 3 },
  { id: "v-taiouchuu", japanese: "対応中", reading: "たいおうちゅう", meaning: "currently handling", category: "Customer Service", month: 3 },
  { id: "v-shikyuu", japanese: "至急", reading: "しきゅう", meaning: "urgent", category: "Customer Service", month: 3 },
  { id: "v-kyoushuku", japanese: "恐縮", reading: "きょうしゅく", meaning: "much obliged / sorry to trouble you", category: "Set Phrases", month: 6 },
  { id: "v-moushiwake", japanese: "申し訳", reading: "もうしわけ", meaning: "apology (root of 申し訳ございません)", category: "Set Phrases", month: 3 },
  // Week 4 D1 — appointments
  { id: "v-yakusoku", japanese: "約束", reading: "やくそく", meaning: "promise / appointment", category: "Appointments", month: 2 },
  { id: "v-menkai", japanese: "面会", reading: "めんかい", meaning: "meeting / interview (with someone)", category: "Appointments", month: 2 },
  { id: "v-houmon", japanese: "訪問", reading: "ほうもん", meaning: "visit", category: "Appointments", month: 2 },
  { id: "v-tsugou", japanese: "都合", reading: "つごう", meaning: "convenience / circumstances", category: "Appointments", month: 2 },
  { id: "v-nittei", japanese: "日程", reading: "にってい", meaning: "schedule / itinerary", category: "Appointments", month: 2 },
  { id: "v-kakutei", japanese: "確定", reading: "かくてい", meaning: "confirmed / finalized", category: "Appointments", month: 2 },
  { id: "v-cancel", japanese: "キャンセル", reading: "キャンセル", meaning: "cancellation", category: "Appointments", month: 2 },
  { id: "v-aki", japanese: "空き", reading: "あき", meaning: "vacancy / opening", category: "Appointments", month: 2 },
  { id: "v-chousei", japanese: "調整", reading: "ちょうせい", meaning: "adjustment / coordination", category: "Appointments", month: 2 },
  // Week 4 D2 — meetings
  { id: "v-gidai", japanese: "議題", reading: "ぎだい", meaning: "agenda item", category: "Meetings", month: 4 },
  { id: "v-kettei", japanese: "決定", reading: "けってい", meaning: "decision", category: "Meetings", month: 4 },
  { id: "v-iken", japanese: "意見", reading: "いけん", meaning: "opinion", category: "Meetings", month: 4 },
  { id: "v-sansei", japanese: "賛成", reading: "さんせい", meaning: "agreement / in favor", category: "Meetings", month: 4 },
  { id: "v-hantai", japanese: "反対", reading: "はんたい", meaning: "opposition / against", category: "Meetings", month: 4 },
  { id: "v-teian", japanese: "提案", reading: "ていあん", meaning: "proposal", category: "Meetings", month: 4 },
  { id: "v-gijiroku", japanese: "議事録", reading: "ぎじろく", meaning: "meeting minutes", category: "Meetings", month: 4 },
  { id: "v-shussekisha", japanese: "出席者", reading: "しゅっせきしゃ", meaning: "attendee", category: "Meetings", month: 4 },
  { id: "v-shikai", japanese: "司会", reading: "しかい", meaning: "moderator / chair", category: "Meetings", month: 4 },
  // Week 4 D3 — data/charts
  { id: "v-wariai", japanese: "割合", reading: "わりあい", meaning: "proportion / ratio", category: "Charts & Data", month: 4 },
  { id: "v-zouka", japanese: "増加", reading: "ぞうか", meaning: "increase", category: "Charts & Data", month: 4 },
  { id: "v-genshou", japanese: "減少", reading: "げんしょう", meaning: "decrease", category: "Charts & Data", month: 4 },
  { id: "v-ijou", japanese: "以上", reading: "いじょう", meaning: "and above / or more", category: "Charts & Data", month: 4 },
  { id: "v-ika", japanese: "以下", reading: "いか", meaning: "and below / or less", category: "Charts & Data", month: 4 },
  { id: "v-goukei", japanese: "合計", reading: "ごうけい", meaning: "total", category: "Charts & Data", month: 4 },
  { id: "v-heikin", japanese: "平均", reading: "へいきん", meaning: "average", category: "Charts & Data", month: 4 },
  { id: "v-graph", japanese: "グラフ", reading: "グラフ", meaning: "graph", category: "Charts & Data", month: 4 },
  { id: "v-hyou", japanese: "表", reading: "ひょう", meaning: "table / chart", category: "Charts & Data", month: 4 },
  { id: "v-percent", japanese: "パーセント", reading: "パーセント", meaning: "percent", category: "Charts & Data", month: 4 },
  // Part 8 extra cluster examples not already covered
  { id: "v-kaigishitsu", japanese: "会議室", reading: "かいぎしつ", meaning: "meeting room", category: "Office & People", month: 1 },
  { id: "v-uriage", japanese: "売上", reading: "うりあげ", meaning: "sales revenue", category: "Sales", month: 4 },
  { id: "v-nouhin", japanese: "納品", reading: "のうひん", meaning: "delivery of goods", category: "Delivery", month: 4 },
  { id: "v-hacchuu", japanese: "発注", reading: "はっちゅう", meaning: "placing an order", category: "Sales", month: 4 },
  { id: "v-haisou", japanese: "配送", reading: "はいそう", meaning: "delivery / shipping", category: "Delivery", month: 5 },
  { id: "v-chien", japanese: "遅延", reading: "ちえん", meaning: "delay", category: "Delivery", month: 5 },
  { id: "v-touchaku", japanese: "到着", reading: "とうちゃく", meaning: "arrival", category: "Delivery", month: 5 },
  { id: "v-kisoku", japanese: "規則", reading: "きそく", meaning: "rule / regulation", category: "Workplace Rules", month: 1 },
  { id: "v-kyoka", japanese: "許可", reading: "きょか", meaning: "permission", category: "Workplace Rules", month: 1 },
  { id: "v-shinsei", japanese: "申請", reading: "しんせい", meaning: "application / request (formal)", category: "Workplace Rules", month: 1 },
  { id: "v-shouchi", japanese: "承知", reading: "しょうち", meaning: "understanding / consent (root of 承知しました)", category: "Confirmation & Response", month: 1 },
  { id: "v-ryoukai", japanese: "了解", reading: "りょうかい", meaning: "understood / roger", category: "Confirmation & Response", month: 1 },
];

export const vocabCategoryTargets: { category: string; month: number; target: number }[] = [
  { category: "Office & People", month: 1, target: 200 },
  { category: "Scheduling & Deadlines", month: 2, target: 250 },
  { category: "Telephone", month: 3, target: 60 },
  { category: "Customer Service & Complaints", month: 3, target: 240 },
  { category: "Meetings", month: 4, target: 60 },
  { category: "Sales & Delivery", month: 4, target: 300 },
  { category: "Accounting", month: 4, target: 60 },
  { category: "Problems & Solutions", month: 5, target: 250 },
  { category: "Transport & Logistics", month: 5, target: 60 },
  { category: "Set Phrases (review)", month: 6, target: 250 },
];

export const vocabTotalTarget = 1800; // Source: Part 8 — total after 6 months
export const vocabWeeklyTarget = { min: 60, max: 80 }; // Source: Part 8
export const vocabDailyTarget = { min: 15, max: 20 }; // Source: Part 8

export function vocabCategories() {
  return Array.from(new Set(vocabulary.map((v) => v.category))).sort();
}
