import { DetailedSession } from "./types";

// Source: Part 27 — First Four Weeks in Extreme Detail (16 sessions, verbatim from source)
export const detailedSessions: DetailedSession[] = [
  {
    week: 1, day: 1, title: "Foundation",
    objective: "Lock in です/ます, は/が/を, and start reading numbers/time.",
    grammar: "です/ます sentences; は (topic) vs が (subject); を (object). Watch: Japanese Ammo with Misa \"は vs が\".",
    vocabulary: "Office basics set 1 (10): 会社, 仕事, 会議, 資料, 電話, 部長, 課長, 同僚, 名前, 今日.",
    kanji: "Numbers 一〜十, 百, 千 + 円 (recognition).",
    businessPhrases: "お疲れ様です / おはようございます / お先に失礼します.",
    listening: "Comprehensible Japanese – Complete Beginner, 1 video (no subs, then once more).",
    reading: "Hiragana/katakana speed check; read the 10 new words in kana+kanji.",
    bjtPractice: "Run the official CBT demo once to see the interface.",
    shadowing: "Shadow the beginner video, 10 min, with transcript.",
    realLifeMission: "Mission 1 (note 3 コンビニ greeting phrases).",
    anki: "Create decks; add today's 10 vocab + 3 phrases. Do 0 reviews (day 1).",
    homework: "Re-read the grammar notes; write 5 です/ます sentences about your day.",
    endOfSessionTest: "Self-quiz the 10 words + 3 phrases (aim 8/10).",
  },
  {
    week: 1, day: 2, title: "Listening",
    objective: "Train ear to slow dialogue; identify speakers.",
    grammar: "(review only) です/ます, particles.",
    vocabulary: "Office set 2 (10): 時間, 予定, 明日, 昨日, 午前, 午後, 週, 月, 曜日, 休み.",
    kanji: "年 月 日 時 分 (dates/time).",
    businessPhrases: "承知しました / かしこまりました (accepting instructions).",
    listening: "Intensive method (Part 12) on 1 JapanesePod101 beginner dialogue.",
    reading: "Read a simple schedule/timetable image; find one time.",
    bjtPractice: "Watch official Part I sample audio; just observe.",
    shadowing: "Shadow the JPod101 dialogue, 12 min, transcript first then without.",
    realLifeMission: "Mission 2 prep (find 3 APU notices to read D3).",
    anki: "Add 10 vocab + 2 phrases; do all reviews.",
    homework: "Write the situation + speakers of today's dialogue in one line.",
    endOfSessionTest: "Listening: re-play clip, answer 3 comprehension Qs.",
  },
  {
    week: 1, day: 3, title: "Reading & Keigo",
    objective: "Read a short notice; grasp the 3 keigo types by name.",
    grammar: "て-form introduction (group 1/2/irregular).",
    vocabulary: "Scheduling set (10): 締め切り, 期限, 変更, 参加, 出席, 欠席, 開始, 終了, 場所, 連絡.",
    kanji: "会 社 部 課 議 (company/meeting).",
    businessPhrases: "少々お待ちください / 確認いたします.",
    keigo: "Learn the 3 types (teineigo/sonkeigo/kenjougo) — recognition only. Watch Nihongo no Mori keigo intro.",
    listening: "One short Comprehensible Japanese clip (must-do 25 min block).",
    reading: "Read 2 real APU notices (Mission 2); find purpose + any date.",
    bjtPractice: "—",
    shadowing: "Shadow one keigo phrase set, 10 min.",
    realLifeMission: "Mission 2 (read 3 notices, translate one).",
    anki: "Add 10 vocab + 2 phrases; all reviews.",
    homework: "Convert 5 plain verbs to て-form.",
    endOfSessionTest: "Keigo: label 6 sample lines as teineigo/sonkeigo/kenjougo.",
  },
  {
    week: 1, day: 4, title: "BJT & Test",
    objective: "First real Part I Situational set + week-1 test.",
    grammar: "(review) particles + て-form.",
    vocabulary: "Review week 1 words (no new).",
    kanji: "Review week 1 kanji.",
    businessPhrases: "Review all week-1 phrases.",
    listening: "Part I Situational — official samples, attempt 5 items.",
    reading: "Re-read one notice, timed.",
    bjtPractice: "Part I Situational sample set; log every wrong answer.",
    shadowing: "Shadow any clip you found hardest this week, 10 min.",
    realLifeMission: "Mission 3 (count workplace phrases at Lawson).",
    anki: "No new cards; clear all reviews.",
    homework: "Fill mistake log for BJT items.",
    endOfSessionTest: "WEEK 1 TEST (all skills, ~40 min). Score + band.",
  },
  {
    week: 2, day: 1, title: "Foundation",
    objective: "Verb groups + に/で/へ; office vocab deepens.",
    grammar: "に (time/target) / で (place/means) / へ (direction); verb groups.",
    vocabulary: "People/roles (10): 社員, 上司, 部下, 担当, お客様, 取引先, 社長, 受付, 事務, 営業.",
    kanji: "書 類 報 告 (documents/report).",
    businessPhrases: "お世話になっております.",
    listening: "Comprehensible Japanese beginner, 1 video.",
    reading: "Read a name card / simple sign.",
    bjtPractice: "—",
    shadowing: "Shadow the video, 12 min.",
    realLifeMission: "Mission 4 (ask a staff member one question in Japanese).",
    anki: "10 vocab + 1 phrase; all reviews.",
    homework: "Write 5 sentences using に/で/へ.",
    endOfSessionTest: "Vocab quiz 10.",
  },
  {
    week: 2, day: 2, title: "Listening",
    objective: "Catch times/dates in dialogue.",
    grammar: "(review) verb groups.",
    vocabulary: "Scheduling 2 (10): 予約, 打ち合わせ, 会場, 資料作成, 提出, 準備, 遅刻, 早退, 残業, 出張.",
    kanji: "予 定 締 切 (schedule).",
    businessPhrases: "恐れ入りますが.",
    listening: "Intensive method on a JPod101 dialogue with times/dates.",
    reading: "Schedule image: extract 2 times.",
    bjtPractice: "Part I Conversational — attempt 5 items.",
    shadowing: "Shadow dialogue, 12 min.",
    realLifeMission: "Mission 5 (use 少々お待ちください or 確認いたします at Lawson).",
    anki: "10 vocab + 1 phrase; reviews.",
    homework: "Note the decision made in the dialogue.",
    endOfSessionTest: "Listening: 3 Qs on times/dates.",
  },
  {
    week: 2, day: 3, title: "Reading & Keigo",
    objective: "Email openings; first sonkeigo/kenjougo verb pairs.",
    grammar: "〜ています (ongoing/state).",
    vocabulary: "Reports/orders (10): 報告, 連絡, 相談, 注文, 依頼, 確認, 承認, 見積, 請求, 支払.",
    kanji: "確 認 依 頼 (confirm/request).",
    businessPhrases: "Email opening: お世話になっております + name/company.",
    keigo: "Verb pairs: 行く→伺う/いらっしゃる; 見る→拝見する/ご覧になる.",
    listening: "Short must-do clip, 25 min.",
    reading: "Read a short business email opening + purpose.",
    bjtPractice: "—",
    shadowing: "Shadow email-reading aloud, 10 min.",
    realLifeMission: "Mission 6 (understand one announcement).",
    anki: "10 vocab + email phrase; reviews.",
    homework: "Write an email opening line to a client.",
    endOfSessionTest: "Keigo: match 6 verbs to humble/respectful forms.",
  },
  {
    week: 2, day: 4, title: "BJT & Test",
    objective: "Mixed Part I set + week-2 test.",
    grammar: "(review).",
    vocabulary: "Review week 2.",
    kanji: "Review week 2.",
    businessPhrases: "Review.",
    listening: "Part I mixed (Situational + Conversational), 8 items.",
    reading: "Timed short notice.",
    bjtPractice: "Part I mixed set; mistake log.",
    shadowing: "Hardest clip, 10 min.",
    realLifeMission: "Mission 7 (read label/price sign, note counters).",
    anki: "No new; clear reviews.",
    homework: "Mistake-log review; tally categories.",
    endOfSessionTest: "WEEK 2 TEST. Score + band.",
  },
  {
    week: 3, day: 1, title: "Foundation",
    objective: "past/negative + 〜たい; telephone vocab starts.",
    grammar: "Past & negative (ました/ません/でした); 〜たいです.",
    vocabulary: "Telephone (10): 電話, 内線, 折り返し, 伝言, 番号, 呼び出し, 通話, 留守, 不在, 担当者.",
    kanji: "電 話 番 号 (phone).",
    businessPhrases: "いたします / おります (humble helpers).",
    listening: "Beginner video, 1.",
    reading: "Read a phone-message form.",
    bjtPractice: "—",
    shadowing: "12 min.",
    realLifeMission: "Mission 8 (full transaction as customer in Japanese).",
    anki: "10 vocab + 1 phrase; reviews.",
    homework: "5 past/negative sentences.",
    endOfSessionTest: "Vocab 10.",
  },
  {
    week: 3, day: 2, title: "Listening",
    objective: "First monologues; who-decides tracking.",
    grammar: "(review) past/neg.",
    vocabulary: "Customer svc (10): 対応, 苦情, 謝罪, 交換, 返品, 在庫, 商品, 案内, 受付, 待ち時間.",
    kanji: "客 対 応 (customer).",
    businessPhrases: "Telephone: 少々お待ちください + 確認いたします in a call.",
    listening: "Intensive method on a short monologue (JPod101).",
    reading: "Notice with a date; find it fast.",
    bjtPractice: "Part I Conversational, 5 items.",
    shadowing: "12 min.",
    realLifeMission: "Mission 9 (observe phone/intercom phrases).",
    anki: "10 vocab + 1; reviews.",
    homework: "Write 3 facts from the monologue.",
    endOfSessionTest: "Listening 3 Qs.",
  },
  {
    week: 3, day: 3, title: "Reading & Keigo",
    objective: "Email body + telephone keigo.",
    grammar: "と / ば conditionals (intro).",
    vocabulary: "Complaints/apology (10): 問題, 原因, 対策, 解決, 迷惑, 訂正, 対応中, 至急, 恐縮, 申し訳.",
    kanji: "問 題 原 因 (problem/cause).",
    businessPhrases: "申し訳ございません (apology).",
    keigo: "Telephone keigo set: どちら様でしょうか / 席を外しております / 伝言を承ります.",
    listening: "Must-do clip, 25 min.",
    reading: "Read an email body (request); find the ask.",
    bjtPractice: "—",
    shadowing: "Shadow phone keigo, 10 min.",
    realLifeMission: "Mission 10 (two-part question to APU staff).",
    anki: "10 vocab + 1; reviews.",
    homework: "Write a 3-line apology email.",
    endOfSessionTest: "Keigo: 6 phone-situation items.",
  },
  {
    week: 3, day: 4, title: "BJT & Test",
    objective: "Add Part III Vocab/Grammar; week-3 test.",
    grammar: "(review) conditionals.",
    vocabulary: "Review week 3.",
    kanji: "Review week 3.",
    businessPhrases: "Review.",
    listening: "Part I set, 8 items.",
    reading: "Part III Vocabulary/Grammar, 5 items.",
    bjtPractice: "Part III V/G + Part I; mistake log.",
    shadowing: "10 min.",
    realLifeMission: "Mission 11 (read a university email; find purpose + deadline).",
    anki: "No new; reviews.",
    homework: "Tally mistake log.",
    endOfSessionTest: "WEEK 3 TEST. Score + band.",
  },
  {
    week: 4, day: 1, title: "Foundation",
    objective: "〜てください requests; consolidate.",
    grammar: "〜てください (request) + 〜ないでください.",
    vocabulary: "Appointments (10): 約束, 面会, 訪問, 都合, 日程, 変更, 確定, キャンセル, 空き, 調整.",
    kanji: "予 約 面 会 訪 問 (appointments).",
    businessPhrases: "よろしくお願いいたします (closing).",
    listening: "Beginner video, 1.",
    reading: "Read appointment note.",
    bjtPractice: "—",
    shadowing: "12 min.",
    realLifeMission: "Mission 12 (handle a Lawson request politely; log phrases).",
    anki: "10 vocab + 1; reviews.",
    homework: "5 〜てください sentences.",
    endOfSessionTest: "Vocab 10.",
  },
  {
    week: 4, day: 2, title: "Listening",
    objective: "Changed-detail drill; appointment dialogues.",
    grammar: "(review) requests.",
    vocabulary: "Meetings (10): 会議, 議題, 決定, 意見, 賛成, 反対, 提案, 議事録, 出席者, 司会.",
    kanji: "決 定 意 見 (decision/opinion).",
    businessPhrases: "Meeting: おっしゃる通りです / 確かに〜ですが.",
    listening: "Intensive method on an appointment dialogue (catch the changed time).",
    reading: "Two similar schedule rows; pick the right one.",
    bjtPractice: "Part I timed (short), 8 items.",
    shadowing: "12 min.",
    realLifeMission: "Mission 13 (observe register: manager→junior vs →customer).",
    anki: "10 vocab + 1; reviews.",
    homework: "Note original vs changed detail.",
    endOfSessionTest: "Listening 3 Qs.",
  },
  {
    week: 4, day: 3, title: "Reading & Keigo",
    objective: "Simple schedule reading + mixed keigo.",
    grammar: "〜てもいいですか (permission).",
    vocabulary: "Data/charts (10): 割合, 増加, 減少, 以上, 以下, 合計, 平均, グラフ, 表, パーセント.",
    kanji: "増 減 割 合 (quantities).",
    businessPhrases: "Cushion: 恐れ入りますが + request.",
    keigo: "Mixed drill: choose sonkeigo vs kenjougo for 6 given actions.",
    listening: "Must-do clip, 25 min.",
    reading: "Read a simple schedule + a small table; extract 2 values.",
    bjtPractice: "—",
    shadowing: "10 min.",
    realLifeMission: "Mission 14 (extract 3 numbers from a flyer fast).",
    anki: "10 vocab + 1; reviews.",
    homework: "Write a permission request to a manager.",
    endOfSessionTest: "Keigo mixed 6 items.",
  },
  {
    week: 4, day: 4, title: "BJT & MONTH-1 CHECK",
    objective: "Month-1 checkpoint + Part I timed x2.",
    grammar: "(review month 1).",
    vocabulary: "Review all month-1 clusters.",
    kanji: "Review all month-1 kanji.",
    businessPhrases: "Review all month-1 phrases.",
    listening: "Part I timed set x2 (Situational + Conversational).",
    reading: "Part III V/G, 5 items, timed.",
    bjtPractice: "Part I Situational x2; mistake log + category tally.",
    shadowing: "Hardest month-1 clip, 10 min.",
    realLifeMission: "Reflect on missions 1–14 so far.",
    anki: "No new; clear reviews.",
    homework: "Compare week-1→week-4 test scores; note trend.",
    endOfSessionTest: "MONTH-1 CHECKPOINT (Part 23 targets). Decide: on-track or remediate.",
  },
];

export function getSession(week: number, day: number) {
  return detailedSessions.find((s) => s.week === week && s.day === day);
}

// Source: Part 28 — Day 1, Complete Lesson (minute-by-minute)
export const day1Blocks = [
  { time: "0:00–0:10", minutes: 10, activity: "Set up. Install Anki + create 5 decks (Part 19). Open Jisho, YouTube, and the BJT demo in tabs.", stepTitle: "Set Up" },
  { time: "0:10–0:20", minutes: 10, activity: "Warm-up: read the hiragana/katakana charts aloud once for speed. (No Anki reviews yet — day 1.)", stepTitle: "Warm-up" },
  { time: "0:20–1:05", minutes: 45, activity: "GRAMMAR: です/ます + は/が/を. Watch Japanese Ammo with Misa \"は vs が\" then write 5 です/ます sentences about your day.", stepTitle: "Grammar" },
  { time: "1:05–1:50", minutes: 45, activity: "VOCABULARY: learn the 10 office words (会社, 仕事, 会議, 資料, 電話, 部長, 課長, 同僚, 名前, 今日). Add each to Anki with a Jisho example sentence + audio.", stepTitle: "Vocabulary" },
  { time: "1:50–2:00", minutes: 10, activity: "Break.", stepTitle: "Break" },
  { time: "2:00–2:20", minutes: 20, activity: "KANJI: recognise 一〜十, 百, 千, 円. Read them inside 千円, 百円, 三時.", stepTitle: "Kanji" },
  { time: "2:20–2:30", minutes: 10, activity: "BUSINESS PHRASES: お疲れ様です / おはようございます / お先に失礼します. Add to Anki.", stepTitle: "Business Phrases" },
  { time: "2:30–2:55", minutes: 25, activity: "LISTENING + SHADOWING: Comprehensible Japanese \"Complete Beginner\" video — watch once no subs, once with; then shadow 10 min.", stepTitle: "Listening + Shadowing" },
  { time: "2:55–3:00", minutes: 5, activity: "MINI-TEST + LOG: self-quiz 10 words + 3 phrases (aim 8/10). Jot tomorrow's start point. Do Mission 1 on your next Lawson shift.", stepTitle: "Mini-Test + Log" },
];

export const day1Links = [
  { label: "Anki download", url: "https://apps.ankiweb.net/" },
  { label: "Japanese Ammo with Misa — は vs が (search on channel)", url: "https://www.youtube.com/@JapaneseAmmowithMisa" },
  { label: "Comprehensible Japanese — Complete Beginner", url: "https://www.youtube.com/@cijapanese" },
  { label: "Jisho dictionary", url: "https://jisho.org/" },
  { label: "BJT official CBT demo (browse if time permits)", url: "https://www.kanken.or.jp/bjt/cbt_demo/" },
];
